default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: leggy_dev

test:
  <<: *default
  database: leggy_test

production:
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

