# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

song_info = [
  { content: "消音" },
  { content: "消音結束" },
]
Songinfo.create!(song_info)

singer = [
  {
    name: "",
    name_translation: "",
  },
  {
    name: "宋冬野",
    name_translation: "",
  },
  {
    name: "徐佳瑩",
    name_translation: "",
  },
  {
    name: "蔡健雅",
    name_translation: "",
  },
  {
    name: "解偉苓",
    name_translation: "",
  },
  {
    name: "梁詠琪",
    name_translation: "",
  },
  {
    name: "anNina",
    name_translation: "",
  },
  {
    name: "荒井由実",
    name_translation: "",
  },
  {
    name: "へっぽこ六弦使い",
    name_translation: "",
  },
  {
    name: "FREENOTE",
    name_translation: "",
  },
  {
    name: "偽物語&吉幾三",
    name_translation: "",
  },
  {
    name: "初音ミクAppend(Dark)",
    name_translation: "",
  },
  {
    name: "keeno",
    name_translation: "",
  },
  {
    name: "楊乃文",
    name_translation: "",
  },
  {
    name: "陳綺貞",
    name_translation: "",
  },
  {
    name: "梁靜茹",
    name_translation: "",
  },
  {
    name: "米津玄師",
    name_translation: "",
  },
  {
    name: "初音ミク",
    name_translation: "",
  },
  {
    name: "ジミーサムP",
    name_translation: "",
  },
  {
    name: "におP",
    name_translation: "",
  },
  {
    name: "GUMI",
    name_translation: "",
  },
  {
    name: "baker",
    name_translation: "",
  },
  {
    name: "土岐麻子",
    name_translation: "",
  },
  {
    name: "sasakure.UK",
    name_translation: "",
  },
  {
    name: "光GENJI",
    name_translation: "",
  },
  {
    name: "鏡音レン",
    name_translation: "",
  },
  {
    name: "DATEKEN",
    name_translation: "",
  },
  {
    name: "巡音ルカ",
    name_translation: "",
  },
  {
    name: "ささくれP",
    name_translation: "",
  },
  {
    name: "宮沢もよよ",
    name_translation: "",
  },
  {
    name: "ATOLS",
    name_translation: "",
  },
  {
    name: "青木月光",
    name_translation: "",
  },
  {
    name: "すこっぷ",
    name_translation: "",
  },
  {
    name: "清浦夏実",
    name_translation: "",
  },
  {
    name: "東京事変",
    name_translation: "",
  },
  {
    name: "初音ミクAppend",
    name_translation: "",
  },
  {
    name: "ねこぼーろ/ササノマリイ sasanomaly",
    name_translation: "",
  },
  {
    name: "ピノキオP",
    name_translation: "",
  },
  {
    name: "ハチ",
    name_translation: "",
  },
  {
    name: "小南泰葉",
    name_translation: "",
  },
  {
    name: "蝶々P",
    name_translation: "",
  },
  {
    name: "Lucy Rose",
    name_translation: "",
  },
  {
    name: "電ポルP",
    name_translation: "",
  },
  {
    name: "石川智晶",
    name_translation: "",
  },
  {
    name: "40㍍P",
    name_translation: "",
  },
  {
    name: "ほえほえP",
    name_translation: "",
  },
  {
    name: "ぽわぽわP",
    name_translation: "",
  },
  {
    name: "ジミーサムP",
    name_translation: "",
  },
  {
    name: "Aiko",
    name_translation: "",
  },
  {
    name: "Tizzy Bac",
    name_translation: "",
  },
  {
    name: "とあ",
    name_translation: "",
  },
  {
    name: "東森幼幼",
    name_translation: "",
  },
  {
    name: "茶太",
    name_translation: "",
  },
  {
    name: "IA",
    name_translation: "",
  },
  {
    name: "じん/自然の敵P",
    name_translation: "",
  },
  {
    name: "Loco Roco",
    name_translation: "",
  },
  {
    name: "張震嶽",
    name_translation: "",
  },
  {
    name: "魏如昀",
    name_translation: "",
  },
  {
    name: "Taylor Swift",
    name_translation: "",
  },
  {
    name: "莫文蔚",
    name_translation: "",
  },
  {
    name: "羊毛とおはな",
    name_translation: "",
  },
  {
    name: "陶喆",
    name_translation: "",
  },
  {
    name: "張惠妹",
    name_translation: "",
  },
  {
    name: "Keno",
    name_translation: "",
  },
  {
    name: "初音ミクAppend(Soft)",
    name_translation: "",
  },
  {
    name: "きゃりーぱみゅぱみゅ",
    name_translation: "",
  },
  {
    name: "におP",
    name_translation: "",
  },
  {
    name: "古川本舗",
    name_translation: "",
  },
  {
    name: "Radwimps",
    name_translation: "",
  },
  {
    name: "Paolino",
    name_translation: "",
  },
  {
    name: "フェイP",
    name_translation: "",
  },
  {
    name: "ZONE",
    name_translation: "",
  },
  {
    name: "高橋洋子",
    name_translation: "",
  },
  {
    name: "DECO*27",
    name_translation: "",
  },
  {
    name: "妖怪ウォッチ",
    name_translation: "",
  },
  {
    name: "鄧紫棋",
    name_translation: "",
  },
  {
    name: "A-lin",
    name_translation: "",
  },
  {
    name: "Sia",
    name_translation: "",
  },
  {
    name: "千石撫子",
    name_translation: "",
  },
  {
    name: "花澤香菜",
    name_translation: "",
  },
  {
    name: "椎名林檎",
    name_translation: "",
  },
  {
    name: "Do As Infinity",
    name_translation: "",
  },
  {
    name: "洪佩瑜",
    name_translation: "",
  },
  {
    name: "林嘉欣",
    name_translation: "",
  },
  {
    name: "鄭秀文",
    name_translation: "",
  },
  {
    name: "許慧欣",
    name_translation: "",
  },
  {
    name: "孫燕姿",
    name_translation: "",
  },
  {
    name: "蘇慧倫",
    name_translation: "",
  },
  {
    name: "阿杜&江蕙",
    name_translation: "",
  },
  {
    name: "江蕙",
    name_translation: "",
  },
  {
    name: "張秀卿",
    name_translation: "",
  },
  {
    name: "五月天",
    name_translation: "",
  },
  {
    name: "劉若英",
    name_translation: "",
  },
  {
    name: "盧廣仲",
    name_translation: "",
  },
  {
    name: "萬能青年旅店",
    name_translation: "",
  },
  {
    name: "Hello Nico",
    name_translation: "",
  },
  {
    name: "ふわりP",
    name_translation: "",
  },
  {
    name: "miki",
    name_translation: "",
  },
  {
    name: "魏如萱",
    name_translation: "",
  },
  {
    name: "まふまふ",
    name_translation: "",
  },
  {
    name: "CNBLUE",
    name_translation: "",
  },
  {
    name: "新堀奈夕",
    name_translation: "",
  },
  {
    name: "蜉蝣",
    name_translation: "",
  },
  {
    name: "重音テト",
    name_translation: "",
  },
  {
    name: "はるふり",
    name_translation: "",
  },
  {
    name: "大塚愛",
    name_translation: "",
  },
  {
    name: "蕭亞軒&胡彥斌",
    name_translation: "",
  },
  {
    name: "Yui",
    name_translation: "",
  },
  {
    name: "馬渡松子",
    name_translation: "",
  },
  {
    name: "張懸",
    name_translation: "",
  },
  {
    name: "任賢齊",
    name_translation: "",
  },
  {
    name: "棉花糖",
    name_translation: "",
  },
  {
    name: "U-ji",
    name_translation: "",
  },
  {
    name: "鏡音リン、鏡音レン",
    name_translation: "",
  },
  {
    name: "かぴたろう",
    name_translation: "",
  },
  {
    name: "ハンバート ハンバート",
    name_translation: "",
  },
  {
    name: "李千娜",
    name_translation: "",
  },
  {
    name: "蔡依林",
    name_translation: "",
  },
  {
    name: "南拳媽媽",
    name_translation: "",
  },
  {
    name: "平井堅",
    name_translation: "",
  },
  {
    name: "陶晶瑩",
    name_translation: "",
  },
  {
    name: "10日P",
    name_translation: "",
  },
  {
    name: "原田知世",
    name_translation: "",
  },
  {
    name: "Keira Knightley",
    name_translation: "",
  },
  {
    name: "ゆうゆ",
    name_translation: "",
  },
  {
    name: "19's Sound Factory",
    name_translation: "",
  },
  {
    name: "Dixie Flatline",
    name_translation: "",
  },
  {
    name: "高鈴",
    name_translation: "",
  },
  {
    name: "あんしんパパ",
    name_translation: "",
  },
  {
    name: "ドリーミング",
    name_translation: "",
  },
  {
    name: "mao",
    name_translation: "",
  },
  {
    name: "工藤真由",
    name_translation: "",
  },
  {
    name: "MAHO堂",
    name_translation: "",
  },
  {
    name: "TK from 凛として時雨",
    name_translation: "",
  },
  {
    name: "TEMPURA KIDZ",
    name_translation: "",
  },
  {
    name: "At17",
    name_translation: "",
  },
  {
    name: "羅美玲",
    name_translation: "",
  },
  {
    name: "EGOIST",
    name_translation: "",
  },
  {
    name: "MARETU",
    name_translation: "",
  },
  {
    name: "KEI",
    name_translation: "",
  },
  {
    name: "YMCK",
    name_translation: "",
  },
  {
    name: "孝琳",
    name_translation: "",
  },
  {
    name: "DAOKO",
    name_translation: "",
  },
  {
    name: "kz",
    name_translation: "",
  },
  {
    name: "SPITZ",
    name_translation: "",
  },
  {
    name: "らさ",
    name_translation: "",
  },
  {
    name: "天野月子",
    name_translation: "",
  },
  {
    name: "トラボルタP",
    name_translation: "",
  },
  {
    name: "島みやえい子",
    name_translation: "",
  },
  {
    name: "さつき が てんこもり",
    name_translation: "",
  },
  {
    name: "とみー",
    name_translation: "",
  },
  {
    name: "鏡音リン",
    name_translation: "",
  },
  {
    name: "iroha",
    name_translation: "",
  },
  {
    name: "黒うさP",
    name_translation: "",
  },
  {
    name: "中島愛",
    name_translation: "",
  },
  {
    name: "ナノウ",
    name_translation: "",
  },
  {
    name: "supercell",
    name_translation: "",
  },
  {
    name: "やくしまるえつこ",
    name_translation: "",
  },
  {
    name: "えこ。",
    name_translation: "",
  },
  {
    name: "Rie fu",
    name_translation: "",
  },
  {
    name: "Double 2 樂團",
    name_translation: "",
  },
  {
    name: "Nylas",
    name_translation: "",
  },
  {
    name: "Dios/シグナルP",
    name_translation: "",
  },
  {
    name: "レミオロメン",
    name_translation: "",
  },
  {
    name: "kagrra,",
    name_translation: "",
  },
  {
    name: "Supercell",
    name_translation: "",
  },
  {
    name: "SNoW",
    name_translation: "",
  },
  {
    name: "KAITO",
    name_translation: "",
  },
  {
    name: "イントロP",
    name_translation: "",
  },
  {
    name: "手嶌葵",
    name_translation: "",
  },
  {
    name: "井上あずみ",
    name_translation: "",
  },
  {
    name: "氷川きよし",
    name_translation: "",
  },
  {
    name: "宇多田ヒカル",
    name_translation: "",
  },
  {
    name: "戴佩妮",
    name_translation: "",
  },
  {
    name: "ぐにょ",
    name_translation: "",
  },
  {
    name: "伍佰",
    name_translation: "",
  },
  {
    name: "Superfly&秦基博",
    name_translation: "",
  },
  {
    name: "椎名林檎＆椎名純平",
    name_translation: "",
  },
  {
    name: "村人P",
    name_translation: "",
  },
  {
    name: "ノク/Noak",
    name_translation: "",
  },
  {
    name: "紅色リトマス",
    name_translation: "",
  },
  {
    name: "Superfly",
    name_translation: "",
  },
  {
    name: "ポール・ギルバート",
    name_translation: "",
  },
  {
    name: "space cake 太空蛋糕",
    name_translation: "",
  },
  {
    name: "The Shine & Shine & Shine & Shine 閃閃閃閃",
    name_translation: "",
  },
  {
    name: "青森最後の詩人ひろやー",
    name_translation: "",
  },
  {
    name: "CapsLack",
    name_translation: "",
  },
  {
    name: "フジファブリック",
    name_translation: "",
  },
  {
    name: "ORANGE RANGE",
    name_translation: "",
  },
  {
    name: "My Little Airport",
    name_translation: "",
  },
  {
    name: "みきとP",
    name_translation: "",
  },
  {
    name: "秦基博",
    name_translation: "",
  },
  {
    name: "KANA-BOON",
    name_translation: "",
  },
  {
    name: "卜學亮",
    name_translation: "",
  },
  {
    name: "麻吉",
    name_translation: "",
  },
  {
    name: "小安",
    name_translation: "",
  },
  {
    name: "順子",
    name_translation: "",
  },
  {
    name: "まらしぃ",
    name_translation: "",
  },
  {
    name: "上田祐司",
    name_translation: "",
  },
  {
    name: "ハンバートハンバート",
    name_translation: "",
  },
  {
    name: "Angela Aki",
    name_translation: "",
  },
  {
    name: "ACIDMAN",
    name_translation: "",
  },
  {
    name: "江松霖",
    name_translation: "",
  },
  {
    name: "buzzG",
    name_translation: "",
  },
  {
    name: "江松霖",
    name_translation: "",
  },
  {
    name: "侯湘婷",
    name_translation: "",
  },
  {
    name: "コニー",
    name_translation: "",
  },
  {
    name: "鄧麗君",
    name_translation: "",
  },
  {
    name: "Lia",
    name_translation: "",
  },
  {
    name: "大槻真希",
    name_translation: "",
  },
  {
    name: "本田美奈子",
    name_translation: "",
  },
  {
    name: "巡音ルカ・GUMI",
    name_translation: "",
  },
  {
    name: "Easy Pop",
    name_translation: "",
  },
  {
    name: "yatsuhashi",
    name_translation: "",
  },
  {
    name: "?",
    name_translation: "",
  },
  {
    name: "神田沙也加/稲葉菜月/諸星すみれ",
    name_translation: "",
  },
  {
    name: "謝安琪",
    name_translation: "",
  },
  {
    name: "想太",
    name_translation: "",
  },
  {
    name: "Coldplay",
    name_translation: "",
  },
  {
    name: "歌愛ユキ",
    name_translation: "",
  },
  {
    name: "FoZZtone",
    name_translation: "",
  },
  {
    name: "楊千嬅",
    name_translation: "",
  },
  {
    name: "黒髪ストロングP",
    name_translation: "",
  },
  {
    name: "AKINO",
    name_translation: "",
  },
  {
    name: "巡音ルカ(ENG)",
    name_translation: "",
  },
  {
    name: "えり～な",
    name_translation: "",
  },
  {
    name: "GUMI V3(English)",
    name_translation: "",
  },
  {
    name: "Crusher-P",
    name_translation: "",
  },
  {
    name: "のぼる↑P",
    name_translation: "",
  },
  {
    name: "v flower",
    name_translation: "",
  },
  {
    name: "バルーン",
    name_translation: "",
  },
  {
    name: "トーマ",
    name_translation: "",
  },
  {
    name: "偽物語",
    name_translation: "",
  },
  {
    name: "ライブP",
    name_translation: "",
  },
  {
    name: "Crispy脆樂團",
    name_translation: "",
  },
  {
    name: "河仁傑",
    name_translation: "",
  },
  {
    name: "林宥嘉",
    name_translation: "",
  },
  {
    name: "江美琪",
    name_translation: "",
  },
  {
    name: "藤木直人",
    name_translation: "",
  },
  {
    name: "氣志團",
    name_translation: "",
  },
  {
    name: "太妍",
    name_translation: "",
  },
  {
    name: "南方四賤客",
    name_translation: "",
  },
  {
    name: "Spangle call Lilli line",
    name_translation: "",
  },
  {
    name: "aiko",
    name_translation: "",
  },
  {
    name: "騎去哪",
    name_translation: "",
  },
  {
    name: "JUJU",
    name_translation: "",
  },
  {
    name: "Asian kung-fu generation",
    name_translation: "",
  },
  {
    name: "相対性理論",
    name_translation: "",
  },
  {
    name: "中島美嘉",
    name_translation: "",
  },
  {
    name: "もじゃ",
    name_translation: "",
  },
  {
    name: "西沢さんP",
    name_translation: "",
  },
  {
    name: "尹美萊 (太陽的後裔 OST)",
    name_translation: "",
  },
  {
    name: "ナブナ",
    name_translation: "",
  },
  {
    name: "もじゃ / 大柴広己",
    name_translation: "",
  },
  {
    name: "馬頔",
    name_translation: "",
  },
  {
    name: "Lily Chou-Chou",
    name_translation: "",
  },
  {
    name: "Lily Chou Chou",
    name_translation: "",
  },
  {
    name: "あさきのくりむ童話",
    name_translation: "",
  },
  {
    name: "Cicada",
    name_translation: "",
  },
  {
    name: "pg.lost",
    name_translation: "",
  },
  {
    name: "太妍 / TAEYEON / 태연",
    name_translation: "",
  },
  {
    name: "瀬名航",
    name_translation: "",
  },
  {
    name: "コウ",
    name_translation: "",
  },
  {
    name: "結月ゆかり",
    name_translation: "",
  },
  {
    name: "黒澤まどか",
    name_translation: "",
  },
  {
    name: "ナポリP",
    name_translation: "",
  },
  {
    name: "渋谷毅",
    name_translation: "",
  },
  {
    name: "告白 Confession Original Soundtrack",
    name_translation: "",
  },
  {
    name: "BECK",
    name_translation: "",
  },
  {
    name: "朴樹",
    name_translation: "",
  },
  {
    name: "逃跑计划Escape Plan",
    name_translation: "",
  },
  {
    name: "周杰倫",
    name_translation: "",
  },
  {
    name: "whoo × ちょまいよ",
    name_translation: "",
  },
  {
    name: "草東沒有派對",
    name_translation: "",
  },
  {
    name: "阿肆",
    name_translation: "",
  },
  {
    name: "Mandy",
    name_translation: "",
  },
  {
    name: "Mr.Bartender 第三季 ED",
    name_translation: "",
  },
  {
    name: "星野源",
    name_translation: "",
  },
  {
    name: "サカナクション",
    name_translation: "",
  },
  {
    name: "椎名林檎 × 斉藤ネコ",
    name_translation: "",
  },
  {
    name: "amazarashi",
    name_translation: "",
  },
  {
    name: "赤髪",
    name_translation: "",
  }
]
Singer.create!(singer)

song = [
  {
    singer: "宋冬野",
    composer: "",
    title: "夢遺少年",
    lyric_url: "https://mojim.com/twy120593x1x6.htm",
  },
  {
    singer: "徐佳瑩",
    composer: "",
    title: "不怕慶祝",
    lyric_url: "https://mojim.com/twy105599x7x4.htm",
  },
  {
    singer: "徐佳瑩",
    composer: "",
    title: "失落沙洲",
    lyric_url: "https://mojim.com/twy105599x15x10.htm",
  },
  {
    singer: "徐佳瑩",
    composer: "",
    title: "身騎白馬",
    lyric_url: "https://mojim.com/twy105599x15x25.htm",
  },
  {
    singer: "蔡健雅",
    composer: "",
    title: "雙棲動物",
    lyric_url: "https://mojim.com/twy100166x10x1.htm",
  },
  {
    singer: "蔡健雅",
    composer: "",
    title: "無底洞",
    lyric_url: "https://mojim.com/twy100166x8x2.htm",
  },
  {
    singer: "蔡健雅",
    composer: "",
    title: "陌生人",
    lyric_url: "https://mojim.com/tw100166x8.htm#6",
  },
  {
    singer: "蔡健雅",
    composer: "",
    title: "記念",
    lyric_url: "https://mojim.com/twy100166x3x2.htm",
  },
  {
    singer: "蔡健雅",
    composer: "",
    title: "思念",
    lyric_url: "https://mojim.com/twy100166x13x7.htm",
  },
  {
    singer: "解偉苓",
    composer: "",
    title: "放逐愛情",
    lyric_url: "https://mojim.com/twy106559x11x4.htm",
  },
  {
    singer: "徐佳瑩",
    composer: "",
    title: "明天的事情",
    lyric_url: "https://mojim.com/twy105599x11x2.htm",
  },
  {
    singer: "梁詠琪",
    composer: "",
    title: "膽小鬼",
    lyric_url: "https://mojim.com/twy100093x4x2.htm",
  },
  {
    singer: "梁詠琪",
    composer: "",
    title: "Amour",
    lyric_url: "https://mojim.com/twy100093x15x2.htm",
  },
  {
    singer: "anNina",
    composer: "",
    title: "対象a",
    lyric_url: "http://www.kasi-time.com/item-15783.html",
  },
  {
    singer: "荒井由実",
    composer: "",
    title: "やさしさに包まれたなら",
    lyric_url: "http://www.nicovideo.jp/watch/sm16983161?ref=search_key_video",
  },
  {
    singer: "へっぽこ六弦使い",
    composer: "",
    title: "風になる-Acoustic ver.-",
    lyric_url: "http://www.nicovideo.jp/watch/sm16899289",
  },
  {
    singer: "FREENOTE",
    composer: "",
    title: "ラストワルツ",
    lyric_url: "https://mojim.com/twy107777x2x3.htm",
  },
  {
    singer: "偽物語&吉幾三",
    composer: "",
    title: "白金ディスコ",
    lyric_url: "http://www.nicovideo.jp/watch/sm17321142?playlist_type=mylist&group_id=25063698&mylist_sort=1&ref=my_mylist_s1_p1_n74",
  },
  {
    singer: "初音ミクAppend(Dark)",
    composer: "keeno",
    title: "crack",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/12661.html",
  },
  {
    singer: "初音ミクAppend(Dark)",
    composer: "keeno",
    title: "alternate",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/32950.html",
  },
  {
    singer: "初音ミクAppend(Dark)",
    composer: "keeno",
    title: "glow",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/10599.html",
  },
  {
    singer: "初音ミクAppend(Dark)",
    composer: "keeno",
    title: "longing",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13759.html",
  },
  {
    singer: "楊乃文",
    composer: "",
    title: "星星堆滿天",
    lyric_url: "https://mojim.com/twy100142x5x3.htm",
  },
  {
    singer: "楊乃文",
    composer: "",
    title: "女爵",
    lyric_url: "https://mojim.com/twy100142x6x1.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "太陽(immortal)",
    lyric_url: "https://mojim.com/twy100115x21x3.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "距離(distance)",
    lyric_url: "https://mojim.com/twy100115x21x5.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "魚(the edge)",
    lyric_url: "https://mojim.com/twy100115x21x4.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "下個星期去英國(go to England next week)",
    lyric_url: "https://mojim.com/twy100115x21x8.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "我親愛的偏執狂",
    lyric_url: "https://mojim.com/twy100115x6x1.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "太聰明",
    lyric_url: "https://mojim.com/twy100115x6x2.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "小步舞曲",
    lyric_url: "https://mojim.com/twy100115x6x3.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "1234567",
    lyric_url: "https://mojim.com/twy100115x6x4.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "躺在你的衣櫃",
    lyric_url: "https://mojim.com/twy100115x6x6.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "吉他手",
    lyric_url: "https://mojim.com/twy100115x6x8.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "黑眼圈",
    lyric_url: "https://mojim.com/twy100115x6x9.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "小小校歌",
    lyric_url: "https://mojim.com/twy100115x11x2.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "天天想你",
    lyric_url: "https://mojim.com/twy100115x23x22.htm",
  },
  {
    singer: "梁靜茹",
    composer: "",
    title: "可惜不是你",
    lyric_url: "https://mojim.com/twy100095x12x6.htm",
  },
  {
    singer: "米津玄師",
    composer: "",
    title: "アイネクライネ",
    lyric_url: "http://j-lyric.net/artist/a0579b7/l031237.html",
  },
  {
    singer: "米津玄師",
    composer: "",
    title: "メランコリーキッチン",
    lyric_url: "http://j-lyric.net/artist/a0579b7/l031238.html",
  },
  {
    singer: "米津玄師",
    composer: "",
    title: "vivi",
    lyric_url: "http://j-lyric.net/artist/a0579b7/l02f9fb.html",
  },
  {
    singer: "梁靜茹",
    composer: "",
    title: "beautiful",
    lyric_url: "https://mojim.com/twy100095x7x1.htm",
  },
  {
    singer: "初音ミク",
    composer: "ジミーサムP",
    title: "Calc.",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/11898.html",
  },
  {
    singer: "初音ミク",
    composer: "におP",
    title: "Tómur",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13140.html",
  },
  {
    singer: "GUMI",
    composer: "baker",
    title: "違う空",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/6980.html",
  },
  {
    singer: "土岐麻子",
    composer: "sasakure.UK",
    title: "深海のリトルクライ",
    lyric_url: "http://ameblo.jp/gannpurayakidaisuki/entry-11540863429.html",
  },
  {
    singer: "光GENJI",
    composer: "",
    title: "勇気100%",
    lyric_url: "http://www.nicovideo.jp/watch/sm15535417",
  },
  {
    singer: "鏡音レン",
    composer: "DATEKEN",
    title: "なまえのないうた",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/6256.html",
  },
  {
    singer: "巡音ルカ",
    composer: "sasakure.UK",
    title: "ワンダーラスト",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/4137.html",
  },
  {
    singer: "GUMI",
    composer: "ささくれP",
    title: "ぼくらの16Bit戦争",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/5869.html",
  },
  {
    singer: "初音ミク",
    composer: "宮沢もよよ",
    title: "植物園",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/22256.html",
  },
  {
    singer: "初音ミク",
    composer: "ATOLS",
    title: "ブレス",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/11455.html",
  },
  {
    singer: "初音ミク",
    composer: "青木月光",
    title: "夢と葉桜",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/17261.html",
  },
  {
    singer: "初音ミク",
    composer: "すこっぷ",
    title: "ドミノ倒シ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13999.html",
  },
  {
    singer: "清浦夏実",
    composer: "",
    title: "旅の途中",
    lyric_url: "http://www.kasi-time.com/item-28561.html",
  },
  {
    singer: "東京事変",
    composer: "",
    title: "修羅場",
    lyric_url: "http://www.nicovideo.jp/watch/sm17115246",
  },
  {
    singer: "初音ミクAppend",
    composer: "ねこぼーろ/ササノマリイ sasanomaly",
    title: "戯言スピーカー",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/15786.html",
  },
  {
    singer: "初音ミクAppend",
    composer: "ピノキオP",
    title: "ありふれたせかいせいふく",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/21984.html",
  },
  {
    singer: "初音ミク",
    composer: "ハチ",
    title: "clock lock works",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/7433.html",
  },
  {
    singer: "小南泰葉",
    composer: "",
    title: "HOME",
    lyric_url: "https://mojim.com/twy110713x2x5.htm",
  },
  {
    singer: "小南泰葉",
    composer: "",
    title: "Trash",
    lyric_url: "http://www.kasi-time.com/item-63542.html",
  },
  {
    singer: "GUMI",
    composer: "蝶々P",
    title: "心做し",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/28057.html",
  },
  {
    singer: "Lucy Rose",
    composer: "",
    title: "Shiver",
    lyric_url: "http://www.azlyrics.com/lyrics/lucyrose/shiver.html",
  },
  {
    singer: "初音ミク",
    composer: "電ポルP",
    title: "サイノウサンプラー",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13167.html",
  },
  {
    singer: "石川智晶",
    composer: "",
    title: "アンインストール",
    lyric_url: "http://www.kasi-time.com/item-8852.html",
  },
  {
    singer: "GUMI",
    composer: "40㍍P",
    title: "シリョクケンサ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/17600.html",
  },
  {
    singer: "初音ミク",
    composer: "ハチ",
    title: "WORLD'S END UMBRELLA",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/8608.html",
  },
  {
    singer: "初音ミク",
    composer: "ほえほえP",
    title: "うたうたいのうた",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13620.html",
  },
  {
    singer: "初音ミク",
    composer: "ぽわぽわP",
    title: "ストロボラスト",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/14092.html",
  },
  {
    singer: "初音ミク",
    composer: "ジミーサムP",
    title: "Little Traveler",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/3355.html",
  },
  {
    singer: "Aiko",
    composer: "",
    title: "カブトムシ",
    lyric_url: "http://j-lyric.net/artist/a000619/l00091e.html",
  },
  {
    singer: "Tizzy Bac",
    composer: "",
    title: "我不小心",
    lyric_url: "https://mojim.com/twy102598x3x2.htm",
  },
  {
    singer: "Tizzy Bac",
    composer: "",
    title: "我又再度依戀上昨天",
    lyric_url: "https://mojim.com/twy102598x3x5.htm",
  },
  {
    singer: "Tizzy Bac",
    composer: "",
    title: "You'll See",
    lyric_url: "https://mojim.com/twy102598x3x13.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "鞋貓夫人，Madame!!!",
    lyric_url: "https://mojim.com/twy102598x3x12.htm",
  },
  {
    singer: "Tizzy Bac",
    composer: "",
    title: "季後賽",
    lyric_url: "https://mojim.com/twy102598x3x2.htm",
  },
  {
    singer: "Tizzy Bac",
    composer: "",
    title: "瞬間白眼一千遍",
    lyric_url: "https://mojim.com/twy102598x6x11.htm",
  },
  {
    singer: "Tizzy Bac",
    composer: "",
    title: "太陽快跑",
    lyric_url: "https://mojim.com/twy102598x6x13.htm",
  },
  {
    singer: "Tizzy Bac",
    composer: "",
    title: "For the Way I Live",
    lyric_url: "https://mojim.com/twy102598x3x2.htm",
  },
  {
    singer: "Tizzy Bac",
    composer: "",
    title: "鐵之貝克",
    lyric_url: "https://mojim.com/twy102598x6x1.htm",
  },
  {
    singer: "初音ミク",
    composer: "とあ",
    title: "ツギハギスタッカート",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/29529.html",
  },
  {
    singer: "東森幼幼",
    composer: "",
    title: "卡加布列島",
    lyric_url: "https://www.youtube.com/watch?v=9DeBAD_HDBY",
  },
  {
    singer: "茶太",
    composer: "",
    title: "だんご大家族",
    lyric_url: "http://www.nicovideo.jp/watch/sm13697302",
  },
  {
    singer: "IA",
    composer: "じん/自然の敵P",
    title: "アヤノの幸福理論",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/25204.html",
  },
  {
    singer: "Loco Roco",
    composer: "",
    title: "ロコロコのうた",
    lyric_url: "http://www.uta-net.com/song/46763/",
  },
  {
    singer: "初音ミク",
    composer: "ATOLS",
    title: "マカロン",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/22485.html",
  },
  {
    singer: "張震嶽",
    composer: "",
    title: "再見",
    lyric_url: "https://mojim.com/twy100091x17x7.htm",
  },
  {
    singer: "魏如昀",
    composer: "",
    title: "聽見下雨的聲音",
    lyric_url: "https://mojim.com/twy105804x4x1.htm",
  },
  {
    singer: "蔡健雅",
    composer: "",
    title: "若你碰到他",
    lyric_url: "https://mojim.com/twy100166x16x8.htm",
  },
  {
    singer: "Taylor Swift",
    composer: "",
    title: "Red",
    lyric_url: "https://mojim.com/twy105095x13x2.htm",
  },
  {
    singer: "莫文蔚",
    composer: "",
    title: "If",
    lyric_url: "https://mojim.com/tw100098x29.htm",
  },
  {
    singer: "羊毛とおはな",
    composer: "",
    title: "Englishman In New York",
    lyric_url: "http://www.uta-net.com/song/174360/",
  },
  {
    singer: "陶喆",
    composer: "",
    title: "寂寞的季節",
    lyric_url: "https://mojim.com/twy100207x6x14.htm",
  },
  {
    singer: "張惠妹",
    composer: "",
    title: "偏執面",
    lyric_url: "https://mojim.com/twy100090x45x5.htm",
  },
  {
    singer: "張惠妹",
    composer: "",
    title: "三月",
    lyric_url: "https://mojim.com/twy100090x45x3.htm",
  },
  {
    singer: "張惠妹",
    composer: "",
    title: "真實",
    lyric_url: "https://mojim.com/twy100090x18x4.htm",
  },
  {
    singer: "張惠妹",
    composer: "",
    title: "人質",
    lyric_url: "https://mojim.com/twy100090x27x2.htm",
  },
  {
    singer: "Keno",
    composer: "",
    title: "おはよう",
    lyric_url: "http://www.kasi-time.com/item-12377.html",
  },
  {
    singer: "初音ミク",
    composer: "ほえほえP",
    title: "文学少年の憂鬱",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/8153.html",
  },
  {
    singer: "初音ミク",
    composer: "ねこぼーろ/ササノマリイ sasanomaly",
    title: "オノマトペメガネ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/30477.html",
  },
  {
    singer: "初音ミクAppend(Soft)",
    composer: "すこっぷ",
    title: "アイロニ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/21743.html",
  },
  {
    singer: "きゃりーぱみゅぱみゅ",
    composer: "",
    title: "CANDY CANDY",
    lyric_url: "http://j-lyric.net/artist/a055611/l0282b3.html",
  },
  {
    singer: "きゃりーぱみゅぱみゅ",
    composer: "",
    title: "PONPONPON",
    lyric_url: "http://www.nicovideo.jp/watch/sm16388459",
  },
  {
    singer: "初音ミク",
    composer: "におP",
    title: "rain stops, good-bye",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/1889.html",
  },
  {
    singer: "初音ミク",
    composer: "古川本舗",
    title: "Alice",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/6132.html",
  },
  {
    singer: "Radwimps",
    composer: "",
    title: "me me she",
    lyric_url: "http://j-lyric.net/artist/a04ac97/l009860.html",
  },
  {
    singer: "初音ミク",
    composer: "Paolino",
    title: "キミトセカイ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/15739.html",
  },
  {
    singer: "初音ミクAppend",
    composer: "フェイP",
    title: "Souvenir",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/18392.html",
  },
  {
    singer: "ZONE",
    composer: "",
    title: "secret base～君がくれたもの～",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=66287",
  },
  {
    singer: "高橋洋子",
    composer: "",
    title: "残酷な天使のテーゼ",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=58075",
  },
  {
    singer: "初音ミク",
    composer: "DECO*27",
    title: "恋距離遠愛",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/4250.html",
  },
  {
    singer: "GUMI",
    composer: "DECO*27",
    title: "弱虫モンブラン",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/9644.html",
  },
  {
    singer: "初音ミクAppend",
    composer: "ねこぼーろ/ササノマリイ sasanomaly",
    title: "自傷無色",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/24287.html",
  },
  {
    singer: "妖怪ウォッチ",
    composer: "",
    title: "ようかい体操第一",
    lyric_url: "http://www.kasi-time.com/item-71629.html",
  },
  {
    singer: "鄧紫棋",
    composer: "",
    title: "A.I.N.Y",
    lyric_url: "https://mojim.com/twy105703x5x2.htm",
  },
  {
    singer: "A-lin",
    composer: "",
    title: "給我一個理由忘記",
    lyric_url: "https://mojim.com/twy104821x5x2.htm",
  },
  {
    singer: "Sia",
    composer: "",
    title: "Chandelier",
    lyric_url: "http://www.lyricsfreak.com/s/sia/chandelier_21079675.html",
  },
  {
    singer: "東京事変",
    composer: "",
    title: "能動的三分間",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=Z00073",
  },
  {
    singer: "千石撫子",
    composer: "花澤香菜",
    title: "恋爱サーキュレーション",
    lyric_url: "http://www.kasi-time.com/item-46321.html",
  },
  {
    singer: "椎名林檎",
    composer: "",
    title: "長く短い祭",
    lyric_url: "http://kashinavi.com/song_view.html?88670",
  },
  {
    singer: "初音ミク",
    composer: "古川本舗",
    title: "グリグリメガネと月光蟲",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/9870.html",
  },
  {
    singer: "初音ミク",
    composer: "古川本舗",
    title: "girlfriend",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/7557.html",
  },
  {
    singer: "Do As Infinity",
    composer: "",
    title: "遠雷",
    lyric_url: "https://mojim.com/twy100695x6x6.htm",
  },
  {
    singer: "洪佩瑜",
    composer: "",
    title: "踮起腳尖愛",
    lyric_url: "https://mojim.com/twy109442x12x3.htm",
  },
  {
    singer: "林嘉欣",
    composer: "",
    title: "女明星",
    lyric_url: "https://mojim.com/twy100060x4x6.htm",
  },
  {
    singer: "鄭秀文",
    composer: "",
    title: "808",
    lyric_url: "https://mojim.com/twy100170x64x25.htm",
  },
  {
    singer: "許慧欣",
    composer: "",
    title: "愛情抗體",
    lyric_url: "https://mojim.com/twy102128x5x7.htm",
  },
  {
    singer: "孫燕姿",
    composer: "",
    title: "綠光",
    lyric_url: "https://mojim.com/twy100663x19x56.htm",
  },
  {
    singer: "蘇慧倫",
    composer: "",
    title: "鴨子",
    lyric_url: "https://mojim.com/tw100185x3.htm",
  },
  {
    singer: "阿杜&江蕙",
    composer: "",
    title: "夢中的情話",
    lyric_url: "https://mojim.com/twy100229x23x2.htm",
  },
  {
    singer: "江蕙",
    composer: "",
    title: "家後",
    lyric_url: "https://mojim.com/twy100229x51x30.htm",
  },
  {
    singer: "張秀卿",
    composer: "",
    title: "車站",
    lyric_url: "https://mojim.com/twy100086x8x11.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "心中無別人",
    lyric_url: "https://mojim.com/twy100012x2x4.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "雨眠",
    lyric_url: "https://mojim.com/twy100012x2x8.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "溫柔",
    lyric_url: "https://mojim.com/twy100012x2x10.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "憨人",
    lyric_url: "https://mojim.com/twy100012x2x6.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "借問眾神明",
    lyric_url: "https://mojim.com/twy100012x21x28.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "一顆蘋果",
    lyric_url: "https://mojim.com/twy100012x19x16.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "時光機",
    lyric_url: "https://mojim.com/tw100012x13.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "垃圾車",
    lyric_url: "https://mojim.com/twy100012x21x23.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "好不好",
    lyric_url: "https://mojim.com/twy100012x21x20.htm",
  },
  {
    singer: "五月天",
    composer: "",
    title: "I Love You 無望",
    lyric_url: "https://mojim.com/twy100012x21x26.htm",
  },
  {
    singer: "劉若英",
    composer: "",
    title: "聽！是誰在唱歌",
    lyric_url: "https://mojim.com/twy100158x21x12.htm",
  },
  {
    singer: "GUMI",
    composer: "ささくれP",
    title: "カムパネルラ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/7035.html",
  },
  {
    singer: "盧廣仲",
    composer: "",
    title: "100種生活",
    lyric_url: "https://mojim.com/tw105044x4.htm",
  },
  {
    singer: "萬能青年旅店",
    composer: "",
    title: "秦皇島",
    lyric_url: "https://mojim.com/twy109920x1x6.htm",
  },
  {
    singer: "Hello Nico",
    composer: "",
    title: "你是被抹去的那一段風景",
    lyric_url: "https://mojim.com/cny133635x2x2.htm",
  },
  {
    singer: "初音ミク",
    composer: "古川本舗",
    title: "mugs",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/9682.html",
  },
  {
    singer: "GUMI",
    composer: "baker",
    title: "羽",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/6963.html",
  },
  {
    singer: "歌愛ユキ",
    composer: "想太",
    title: "またあした",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/23142.html",
  },
  {
    singer: "miki",
    composer: "古川本舗",
    title: "スーパー・ノヴァ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/7833.html",
  },
  {
    singer: "魏如萱",
    composer: "",
    title: "買你",
    lyric_url: "https://mojim.com/twy105272x2x4.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "每天都是一種練習",
    lyric_url: "https://mojim.com/twy100115x19x6.htm",
  },
  {
    singer: "初音ミク",
    composer: "古川本舗",
    title: "月光食堂",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/12449.html",
  },
  {
    singer: "まふまふ",
    composer: "",
    title: "鏡花水月",
    lyric_url: "https://www.youtube.com/watch?v=FAYXn2urthw",
  },
  {
    singer: "東京事変",
    composer: "",
    title: "透明人間",
    lyric_url: "http://www.nicovideo.jp/watch/sm18317828",
  },
  {
    singer: "CNBLUE",
    composer: "",
    title: "Hey You",
    lyric_url: "https://tw.answers.yahoo.com/question/index?qid=20120428000015KK08767",
  },
  {
    singer: "新堀奈夕",
    composer: "",
    title: "君にスマイル",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=F03256",
  },
  {
    singer: "蜉蝣",
    composer: "",
    title: "腐った海で溺れかけている僕を救ってくれた君",
    lyric_url: "http://j-lyric.net/artist/a04ac94/l009b7a.html",
  },
  {
    singer: "古川本舗",
    composer: "",
    title: "魔法 feat.ちょまいよ",
    lyric_url: "https://ja.chordwiki.org/wiki/%E9%AD%94%E6%B3%95",
  },
  {
    singer: "重音テト",
    composer: "はるふり",
    title: "右に曲ガール",
    lyric_url: "http://www24.atwiki.jp/utauuuta/pages/3228.html",
  },
  {
    singer: "重音テト",
    composer: "はるふり",
    title: "浮遊感",
    lyric_url: "http://www24.atwiki.jp/utauuuta/pages/3444.html",
  },
  {
    singer: "大塚愛",
    composer: "",
    title: "ユメクイ",
    lyric_url: "http://www.kasi-time.com/item-4353.html",
  },
  {
    singer: "張惠妹",
    composer: "",
    title: "掉了",
    lyric_url: "https://mojim.com/twy100090x36x4.htm",
  },
  {
    singer: "蕭亞軒&胡彥斌",
    composer: "",
    title: "進行式",
    lyric_url: "https://mojim.com/twy105032x2x11.htm",
  },
  {
    singer: "Yui",
    composer: "",
    title: "Again",
    lyric_url: "http://www.kasi-time.com/item-42706.html",
  },
  {
    singer: "馬渡松子",
    composer: "",
    title: "微笑みの爆弾",
    lyric_url: "http://www.kasi-time.com/item-32868.html",
  },
  {
    singer: "小南泰葉",
    composer: "",
    title: "3355411",
    lyric_url: "https://mojim.com/twy110713x7x1.htm",
  },
  {
    singer: "張懸",
    composer: "",
    title: "寶貝",
    lyric_url: "https://mojim.com/twy104870x1x2.htm",
  },
  {
    singer: "張懸",
    composer: "",
    title: "喜歡",
    lyric_url: "https://mojim.com/twy104870x3x3.htm",
  },
  {
    singer: "A-lin",
    composer: "",
    title: "等你",
    lyric_url: "https://mojim.com/twy110507x7x3.htm",
  },
  {
    singer: "任賢齊",
    composer: "",
    title: "我是一隻魚",
    lyric_url: "https://mojim.com/twy100028x25x8.htm",
  },
  {
    singer: "任賢齊",
    composer: "",
    title: "春天花會開",
    lyric_url: "https://mojim.com/twy100028x21x4.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "Self",
    lyric_url: "https://mojim.com/twy100115x15x7.htm",
  },
  {
    singer: "棉花糖",
    composer: "",
    title: "2375",
    lyric_url: "https://mojim.com/twy105564x1x2.htm",
  },
  {
    singer: "初音ミク",
    composer: "U-ji",
    title: "Chip Tears",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/2664.html",
  },
  {
    singer: "初音ミク",
    composer: "ささくれP",
    title: "ナキムシピッポ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/11430.html",
  },
  {
    singer: "鏡音リン、鏡音レン",
    composer: "DATEKEN",
    title: "紡唄 -つむぎうた-",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/4190.html",
  },
  {
    singer: "初音ミク",
    composer: "かぴたろう",
    title: "恐山ル・ヴォワール",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/9276.html",
  },
  {
    singer: "初音ミク",
    composer: "40㍍P",
    title: "キミボシ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/7116.html",
  },
  {
    singer: "ハンバート ハンバート",
    composer: "",
    title: "おなじ話",
    lyric_url: "http://j-lyric.net/artist/a0548cb/l02b996.html",
  },
  {
    singer: "ハンバート ハンバート",
    composer: "",
    title: "天井",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=k-130130-063",
  },
  {
    singer: "ハンバート ハンバート",
    composer: "",
    title: "怪物",
    lyric_url: "http://j-lyric.net/artist/a0548cb/l02b992.html",
  },
  {
    singer: "李千娜",
    composer: "",
    title: "愛到站了",
    lyric_url: "https://mojim.com/twy109601x2x1.htm",
  },
  {
    singer: "蔡依林",
    composer: "",
    title: "倒帶",
    lyric_url: "https://mojim.com/twy100163x30x40.htm",
  },
  {
    singer: "梁靜茹",
    composer: "",
    title: "分手快樂",
    lyric_url: "https://mojim.com/twy100095x11x24.htm",
  },
  {
    singer: "南拳媽媽",
    composer: "",
    title: "下雨天",
    lyric_url: "https://mojim.com/twy104324x7x3.htm",
  },
  {
    singer: "平井堅",
    composer: "",
    title: "瞳をとじて",
    lyric_url: "https://mojim.com/twy100977x13x1.htm",
  },
  {
    singer: "陶晶瑩",
    composer: "",
    title: "那些日子",
    lyric_url: "https://mojim.com/twy100120x8x5.htm",
  },
  {
    singer: "GUMI",
    composer: "10日P",
    title: "マーメイド",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/15348.html",
  },
  {
    singer: "原田知世",
    composer: "",
    title: "くちなしの丘",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B26170",
  },
  {
    singer: "Keira Knightley",
    composer: "",
    title: "Lost Stars",
    lyric_url: "http://www.lyriczz.com/lyrics/keira-knightley/229609-lost-stars/",
  },
  {
    singer: "初音ミク",
    composer: "ゆうゆ",
    title: "深海少女",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/11774.html",
  },
  {
    singer: "初音ミク",
    composer: "19's Sound Factory",
    title: "Dear",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/645.html",
  },
  {
    singer: "巡音ルカ",
    composer: "Dixie Flatline",
    title: "Just Be Friends",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/5809.html",
  },
  {
    singer: "高鈴",
    composer: "",
    title: "愛してる",
    lyric_url: "http://www.kasi-time.com/item-45592.html",
  },
  {
    singer: "あんしんパパ",
    composer: "",
    title: "はじめてのチュウ",
    lyric_url: "http://www.kasi-time.com/item-37901.html",
  },
  {
    singer: "ドリーミング",
    composer: "",
    title: "アンパンマンのマーチ",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=E02014",
  },
  {
    singer: "mao",
    composer: "",
    title: "夢をかなえてドラえもん",
    lyric_url: "http://www.kasi-time.com/item-11599.html",
  },
  {
    singer: "工藤真由",
    composer: "",
    title: "ハートキャッチ☆パラダイス！",
    lyric_url: "http://www.kasi-time.com/item-47104.html",
  },
  {
    singer: "MAHO堂",
    composer: "",
    title: "おジャ魔女カーニバル!!",
    lyric_url: "http://www.kasi-time.com/item-4769.html",
  },
  {
    singer: "TK from 凛として時雨",
    composer: "",
    title: "unravel",
    lyric_url: "http://www.kasi-time.com/item-72624.html",
  },
  {
    singer: "TEMPURA KIDZ",
    composer: "",
    title: "One Step",
    lyric_url: "http://www.kasi-time.com/item-65667.html",
  },
  {
    singer: "At17",
    composer: "",
    title: "The Best is Yet to Come",
    lyric_url: "https://mojim.com/twy102377x3x16.htm",
  },
  {
    singer: "羅美玲",
    composer: "",
    title: "愛一直閃亮",
    lyric_url: "https://mojim.com/twy102367x2x6.htm",
  },
  {
    singer: "羅美玲",
    composer: "",
    title: "紅色向日葵",
    lyric_url: "https://mojim.com/twy102367x2x5.htm",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "讓我想一想",
    lyric_url: "https://mojim.com/twy100115x1x1.htm",
  },
  {
    singer: "EGOIST",
    composer: "",
    title: "- Departures ~あなたにおくるアイの歌~",
    lyric_url: "http://www.kasi-time.com/item-57988.html",
  },
  {
    singer: "初音ミク",
    composer: "MARETU",
    title: "うみたがり",
    lyric_url: "http://www.nicovideo.jp/watch/sm26501160",
  },
  {
    singer: "巡音ルカ",
    composer: "KEI",
    title: "Hello, Worker",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/18090.html",
  },
  {
    singer: "YMCK",
    composer: "",
    title: "Magical 8Bit Tour",
    lyric_url: "https://mojim.com/twy141591x3x2.htm",
  },
  {
    singer: "YMCK",
    composer: "",
    title: "夢の中へ",
    lyric_url: "http://www.kget.jp/lyric/67901/%E5%A4%A2%E3%81%AE%E4%B8%AD%E3%81%B8_YMCK",
  },
  {
    singer: "孝琳",
    composer: "",
    title: "hello,goodbye",
    lyric_url: "http://eros90316.pixnet.net/blog/post/55873803-%E2%99%AA%E9%9F%93%E5%8A%87%E3%80%8A%E4%BE%86%E8%87%AA%E6%98%9F%E6%98%9F%E7%9A%84%E4%BD%A0%E3%80%8Bost---%E4%BD%A0%E5%A5%BD%EF%BC%8C%E5%86%8D%E8%A6%8B(%E9%99%84",
  },
  {
    singer: "DAOKO",
    composer: "",
    title: "水星",
    lyric_url: "http://j-lyric.net/artist/a059caa/l0352b7.html",
  },
  {
    singer: "巡音ルカ",
    composer: "ハチ",
    title: "沙上の夢喰い少女",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/9873.html",
  },
  {
    singer: "初音ミク",
    composer: "kz",
    title: "Tell Your World",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/19646.html",
  },
  {
    singer: "椎名林檎",
    composer: "SPITZ",
    title: "スピカ",
    lyric_url: "https://mojim.com/twy100613x7x3.htm",
  },
  {
    singer: "椎名林檎",
    composer: "",
    title: "丸の内サディスティック",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=65571",
  },
  {
    singer: "らさ",
    composer: "ハチ",
    title: "ニルギリ",
    lyric_url: "http://www.nicovideo.jp/watch/sm11225397",
  },
  {
    singer: "初音ミク",
    composer: "ささくれP",
    title: "＊ハロー、プラネット。",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/5355.html",
  },
  {
    singer: "天野月子",
    composer: "",
    title: "箱庭",
    lyric_url: "http://j-lyric.net/artist/a02411e/l011766.html",
  },
  {
    singer: "巡音ルカ",
    composer: "トラボルタP",
    title: "トエト",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/4316.html",
  },
  {
    singer: "島みやえい子",
    composer: "",
    title: "奈落の花",
    lyric_url: "http://www.kasi-time.com/item-15752.html",
  },
  {
    singer: "初音ミク",
    composer: "さつき が てんこもり",
    title: "お断りします",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/10290.html",
  },
  {
    singer: "初音ミク",
    composer: "とみー",
    title: "1925",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/6777.html",
  },
  {
    singer: "GUMI",
    composer: "DECO*27",
    title: "モザイクロール",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/10915.html",
  },
  {
    singer: "初音ミク",
    composer: "DECO*27",
    title: "二息歩行",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/6347.html",
  },
  {
    singer: "鏡音リン",
    composer: "iroha",
    title: "炉心融解",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/3438.html",
  },
  {
    singer: "GUMI",
    composer: "40㍍P",
    title: "キリトリセン",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/14636.html",
  },
  {
    singer: "初音ミク",
    composer: "40㍍P",
    title: "からくりピエロ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/17230.html",
  },
  {
    singer: "初音ミク",
    composer: "黒うさP",
    title: "リスキーゲーム",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13873.html",
  },
  {
    singer: "中島愛",
    composer: "",
    title: "星間飛行",
    lyric_url: "http://www.nicovideo.jp/watch/sm12152033",
  },
  {
    singer: "初音ミクAppend(Soft)",
    composer: "ナノウ",
    title: "ハロ／ハワユ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/10980.html",
  },
  {
    singer: "supercell",
    composer: "",
    title: "君の知らない物語",
    lyric_url: "http://www.nicovideo.jp/watch/nm8108292",
  },
  {
    singer: "やくしまるえつこ",
    composer: "",
    title: "ヴィーナスとジーザス",
    lyric_url: "http://www.kasi-time.com/item-47983.html",
  },
  {
    singer: "初音ミク",
    composer: "えこ。",
    title: "トウキョウト・ロック・シティ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/5723.html",
  },
  {
    singer: "Rie fu",
    composer: "",
    title: "Life is Like a Boat",
    lyric_url: "http://www.kasi-time.com/item-10944.html",
  },
  {
    singer: "初音ミク",
    composer: "KEI",
    title: "「アイラビューアイニジュー」",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13834.html",
  },
  {
    singer: "Double 2 樂團",
    composer: "",
    title: "安全感",
    lyric_url: "https://www.ptt.cc/bbs/Songs/M.1337593468.A.123.html",
  },
  {
    singer: "Nylas",
    composer: "",
    title: "廢物曬太陽",
    lyric_url: "https://mojim.com/twy105980x3x3.htm",
  },
  {
    singer: "平井堅",
    composer: "",
    title: "大きな古時計",
    lyric_url: "https://tw.answers.yahoo.com/question/index?qid=20051208000014KK03240",
  },
  {
    singer: "初音ミク",
    composer: "kz",
    title: "ストロボナイツ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/72.html",
  },
  {
    singer: "GUMI",
    composer: "Dios/シグナルP",
    title: "会いたい",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/11416.html",
  },
  {
    singer: "レミオロメン",
    composer: "",
    title: "粉雪",
    lyric_url: "http://j-lyric.net/artist/a000776/l008cf0.html",
  },
  {
    singer: "kagrra,",
    composer: "",
    title: "うたかた",
    lyric_url: "http://www.kasi-time.com/item-3565.html",
  },
  {
    singer: "Supercell",
    composer: "",
    title: "うたかた花火",
    lyric_url: "http://www.kasi-time.com/item-49570.html",
  },
  {
    singer: "SNoW",
    composer: "",
    title: "逆さまの蝶",
    lyric_url: "http://www.kasi-time.com/item-3779.html",
  },
  {
    singer: "KAITO",
    composer: "イントロP",
    title: "夢懸歌",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/10074.html",
  },
  {
    singer: "手嶌葵",
    composer: "",
    title: "テルーのうた",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B17197",
  },
  {
    singer: "Supercell",
    composer: "",
    title: "夜が明けるよ",
    lyric_url: "http://www.kasi-time.com/item-52919.html",
  },
  {
    singer: "古川本舗",
    composer: "",
    title: "グレゴリオ",
    lyric_url: "http://www.kget.jp/lyric/210337/%E3%82%B0%E3%83%AC%E3%82%B4%E3%83%AA%E3%82%AA_%E5%8F%A4%E5%B7%9D%E6%9C%AC%E8%88%97",
  },
  {
    singer: "陳綺貞",
    composer: "",
    title: "還是會寂寞",
    lyric_url: "https://mojim.com/tw100115x14.htm",
  },
  {
    singer: "井上あずみ",
    composer: "",
    title: "となりのトトロ",
    lyric_url: "http://www.kasi-time.com/item-10626.html",
  },
  {
    singer: "氷川きよし",
    composer: "",
    title: "きよしのズンドコ節",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=52783",
  },
  {
    singer: "宇多田ヒカル",
    composer: "",
    title: "誰かの願いが叶うころ",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B06408",
  },
  {
    singer: "Hello Nico",
    composer: "",
    title: "接下來如何",
    lyric_url: "https://mojim.com/cny133635x2x10.htm",
  },
  {
    singer: "フジファブリック",
    composer: "",
    title: "花",
    lyric_url: "www.kasi-time.com/item-8331.html",
  },
  {
    singer: "戴佩妮",
    composer: "",
    title: "你要的爱",
    lyric_url: "https://mojim.com/twy109442x33x29.htm",
  },
  {
    singer: "初音ミク",
    composer: "ぐにょ",
    title: "福寿草",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/28212.html",
  },
  {
    singer: "伍佰",
    composer: "",
    title: "夏夜晚風",
    lyric_url: "https://mojim.com/twy100026x20x19.htm",
  },
  {
    singer: "Superfly&秦基博",
    composer: "SPITZ",
    title: "楓",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=64988",
  },
  {
    singer: "東京事変",
    composer: "",
    title: "落日",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B11852",
  },
  {
    singer: "東京事変",
    composer: "",
    title: "林檎の唄",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=A00877",
  },
  {
    singer: "東京事変",
    composer: "",
    title: "閃光少女",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=A02583",
  },
  {
    singer: "東京事変",
    composer: "",
    title: "心",
    lyric_url: "http://j-lyric.net/artist/a000682/l002d98.html",
  },
  {
    singer: "椎名林檎＆椎名純平",
    composer: "",
    title: "この世の限り",
    lyric_url: "http://j-lyric.net/artist/a04cb20/l009b46.html",
  },
  {
    singer: "椎名林檎",
    composer: "",
    title: "茎-STEM",
    lyric_url: "https://mojim.com/twy100613x5x5.htm",
  },
  {
    singer: "GUMI",
    composer: "村人P",
    title: "ナキムシロボ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/24099.html",
  },
  {
    singer: "GUMI",
    composer: "ノク/Noak",
    title: "I love you",
    lyric_url: "http://www.nicovideo.jp/watch/sm19051857",
  },
  {
    singer: "初音ミク",
    composer: "ノク/Noak",
    title: "夜とくじら",
    lyric_url: "http://www.nicovideo.jp/watch/sm26495621",
  },
  {
    singer: "初音ミク",
    composer: "ノク/Noak",
    title: "8",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/34561.html",
  },
  {
    singer: "紅色リトマス",
    composer: "",
    title: "凛として咲く花の如く",
    lyric_url: "http://www7.atwiki.jp/bemanilyrics/pages/160.html",
  },
  {
    singer: "初音ミク",
    composer: "ジミーサムP",
    title: "from Y to Y",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/4684.html",
  },
  {
    singer: "Superfly",
    composer: "",
    title: "愛をこめて花束を",
    lyric_url: "http://j-lyric.net/artist/a04cdbd/l00c3b4.html",
  },
  {
    singer: "椎名林檎",
    composer: "",
    title: "ありあまる富",
    lyric_url: "http://j-lyric.net/artist/a00450a/l017598.html",
  },
  {
    singer: "ポール・ギルバート",
    composer: "",
    title: "僕の頭",
    lyric_url: "http://www.nicovideo.jp/watch/sm3631505",
  },
  {
    singer: "蔡依林",
    composer: "",
    title: "說愛你",
    lyric_url: "https://mojim.com/twy100163x22x3.htm",
  },
  {
    singer: "space cake 太空蛋糕",
    composer: "",
    title: "台語歌",
    lyric_url: "https://www.youtube.com/watch?v=0Jxq10VQwnM",
  },
  {
    singer: "The Shine & Shine & Shine & Shine 閃閃閃閃",
    composer: "",
    title: "四月物語",
    lyric_url: "https://www.indievox.com/disc/248",
  },
  {
    singer: "宋冬野",
    composer: "",
    title: "六層樓",
    lyric_url: "https://mojim.com/twy120593x1x7.htm",
  },
  {
    singer: "宋冬野",
    composer: "",
    title: "莉莉安",
    lyric_url: "https://mojim.com/twy120593x1x2.htm",
  },
  {
    singer: "宋冬野",
    composer: "",
    title: "斑馬，斑馬",
    lyric_url: "https://mojim.com/twy120593x1x5.htm",
  },
  {
    singer: "青森最後の詩人ひろやー",
    composer: "",
    title: "新町",
    lyric_url: "https://www.youtube.com/watch?v=GHuz-ebtSpU",
  },
  {
    singer: "初音ミク",
    composer: "CapsLack",
    title: "フェネストラ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/21145.html",
  },
  {
    singer: "張震嶽",
    composer: "",
    title: "無路用的人",
    lyric_url: "https://www.youtube.com/watch?v=i5nuDFtGFoc",
  },
  {
    singer: "フジファブリック",
    composer: "",
    title: "Chocolate Panic",
    lyric_url: "j-lyric.net/artist/a033e7f/l00c131.html",
  },
  {
    singer: "フジファブリック",
    composer: "",
    title: "Cheese Burger",
    lyric_url: "http://www.kasi-time.com/item-16583.html",
  },
  {
    singer: "My Little Airport",
    composer: "",
    title: "悲傷的採購",
    lyric_url: "https://mojim.com/twy104690x4x9.htm",
  },
  {
    singer: "初音ミクAppend",
    composer: "みきとP",
    title: "小夜子",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/17663.html",
  },
  {
    singer: "初音ミク",
    composer: "古川本舗",
    title: "ピアノ・レッスン",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/5725.html",
  },
  {
    singer: "秦基博",
    composer: "",
    title: "Rain",
    lyric_url: "http://www.kasi-time.com/item-66862.html",
  },
  {
    singer: "宇多田ヒカル",
    composer: "",
    title: "Be My Last",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B11389",
  },
  {
    singer: "秦基博",
    composer: "",
    title: "ミルクティー",
    lyric_url: "j-lyric.net/artist/a04c9d1/l00f888.html",
  },
  {
    singer: "秦基博",
    composer: "",
    title: "鱗",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B24567",
  },
  {
    singer: "初音ミク",
    composer: "ハチ",
    title: "リンネ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/11002.html",
  },
  {
    singer: "KANA-BOON",
    composer: "",
    title: "ないものねだり",
    lyric_url: "http://j-lyric.net/artist/a05808c/l02f9ef.html",
  },
  {
    singer: "Do As Infinity",
    composer: "",
    title: "深い森",
    lyric_url: "http://www.kasi-time.com/item-4477.html",
  },
  {
    singer: "Do As Infinity",
    composer: "",
    title: "ROBOT",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B08837",
  },
  {
    singer: "Do As Infinity",
    composer: "",
    title: "楽園",
    lyric_url: "http://www.kasi-time.com/item-4982.html",
  },
  {
    singer: "Do As Infinity",
    composer: "",
    title: "柊",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B05270",
  },
  {
    singer: "Do As Infinity",
    composer: "",
    title: "ブランコ",
    lyric_url: "http://j-lyric.net/artist/a0007b6/l0022ef.html",
  },
  {
    singer: "Do As Infinity",
    composer: "",
    title: "Yesterday & Today",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=65618",
  },
  {
    singer: "卜學亮",
    composer: "",
    title: "子曰",
    lyric_url: "https://mojim.com/twy100234x1x1.htm",
  },
  {
    singer: "麻吉",
    composer: "",
    title: "Jump 2003",
    lyric_url: "https://mojim.com/twy104695x2x2.htm",
  },
  {
    singer: "小安",
    composer: "",
    title: "憂愁",
    lyric_url: "https://mojim.com/twy102519x1x6.htm",
  },
  {
    singer: "順子",
    composer: "",
    title: "寫一首歌",
    lyric_url: "https://mojim.com/twy100129x9x3.htm",
  },
  {
    singer: "初音ミク",
    composer: "ピノキオP",
    title: "空想しょうもない日々",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/32492.html",
  },
  {
    singer: "初音ミクAppend(Dark)",
    composer: "まらしぃ",
    title: "月景色",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/16932.html",
  },
  {
    singer: "上田祐司",
    composer: "",
    title: "希望の宇宙の…",
    lyric_url: "http://j-lyric.net/artist/a04f531/l01ff4f.html",
  },
  {
    singer: "ハンバートハンバート",
    composer: "",
    title: "1時間",
    lyric_url: "http://j-lyric.net/artist/a0548cb/l030edc.html",
  },
  {
    singer: "Angela Aki",
    composer: "",
    title: "This Love",
    lyric_url: "http://www.kasi-time.com/item-1741.html",
  },
  {
    singer: "ACIDMAN",
    composer: "",
    title: "赤橙",
    lyric_url: "http://www.kasi-time.com/item-29312.html",
  },
  {
    singer: "楊乃文",
    composer: "",
    title: "我給的愛",
    lyric_url: "https://mojim.com/twy100142x2x7.htm",
  },
  {
    singer: "江松霖",
    composer: "",
    title: "要變成全世界最勇敢的人",
    lyric_url: "http://webptt.com/m.aspx?n=bbs/guitar/M.1444669501.A.948.html",
  },
  {
    singer: "GUMI",
    composer: "ささくれP",
    title: "tig-hug",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/30541.html",
  },
  {
    singer: "初音ミク",
    composer: "KEI",
    title: "ピエロ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/10612.html",
  },
  {
    singer: "EGOIST",
    composer: "",
    title: "名前のない怪物",
    lyric_url: "http://www.kasi-time.com/item-64737.html",
  },
  {
    singer: "GUMI",
    composer: "buzzG",
    title: "星の唄",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13837.html",
  },
  {
    singer: "莫文蔚",
    composer: "",
    title: "寂寞的戀人啊",
    lyric_url: "https://mojim.com/twy100098x22x12.htm",
  },
  {
    singer: "江松霖",
    composer: "",
    title: "我不害怕",
    lyric_url: "https://www.youtube.com/watch?v=MfvkbnyoZc8",
  },
  {
    singer: "侯湘婷",
    composer: "",
    title: "秋天別來",
    lyric_url: "https://mojim.com/twy100066x1x1.htm",
  },
  {
    singer: "初音ミクAppend(Dark)",
    composer: "電ポルP",
    title: "独りんぼエンヴィー",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/23582.html",
  },
  {
    singer: "Supercell",
    composer: "",
    title: "約束をしよう",
    lyric_url: "http://www.kasi-time.com/item-46405.html",
  },
  {
    singer: "コニー",
    composer: "",
    title: "しゃぼん玉 piano.ver",
    lyric_url: "http://www.nicovideo.jp/watch/sm17711964",
  },
  {
    singer: "鄧麗君",
    composer: "",
    title: "月亮代表我的心",
    lyric_url: "https://mojim.com/twy100463x71x8.htm",
  },
  {
    singer: "Lia",
    composer: "",
    title: "鳥の詩",
    lyric_url: "http://j-lyric.net/artist/a04f78c/l014f73.html",
  },
  {
    singer: "大槻真希",
    composer: "",
    title: "memories",
    lyric_url: "http://www.kasi-time.com/item-15871.html",
  },
  {
    singer: "本田美奈子",
    composer: "",
    title: "風のうた",
    lyric_url: "http://www.kasi-time.com/item-12379.html",
  },
  {
    singer: "巡音ルカ・GUMI",
    composer: "Easy Pop",
    title: "ハッピーシンセサイザ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13141.html",
  },
  {
    singer: "初音ミクAppend",
    composer: "yatsuhashi",
    title: "Opening Theme",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/10032.html",
  },
  {
    singer: "?",
    composer: "",
    title: "fly me to the moon",
    lyric_url: "https://mojim.com/twy108260x7x1.htm",
  },
  {
    singer: "神田沙也加/稲葉菜月/諸星すみれ",
    composer: "",
    title: "雪だるま作ろう",
    lyric_url: "http://j-lyric.net/artist/a058c14/l0314ea.html",
  },
  {
    singer: "謝安琪",
    composer: "",
    title: "囍帖街",
    lyric_url: "https://mojim.com/twy104479x7x1.htm",
  },
  {
    singer: "初音ミク",
    composer: "想太",
    title: "「うそだよね」",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/23144.html",
  },
  {
    singer: "Coldplay",
    composer: "",
    title: "The Scientist",
    lyric_url: "http://www.metrolyrics.com/the-scientist-lyrics-coldplay.html",
  },
  {
    singer: "Coldplay",
    composer: "",
    title: "Yellow",
    lyric_url: "http://www.azlyrics.com/lyrics/coldplay/yellow.html",
  },
  {
    singer: "歌愛ユキ",
    composer: "想太",
    title: "「いかないで」",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/27027.html",
  },
  {
    singer: "初音ミク",
    composer: "ぽわぽわP",
    title: "そらのサカナ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/12053.html",
  },
  {
    singer: "FoZZtone",
    composer: "",
    title: "ホールケーキ",
    lyric_url: "http://www.kasi-time.com/item-43374.html",
  },
  {
    singer: "楊千嬅",
    composer: "",
    title: "可惜我是水瓶座",
    lyric_url: "https://mojim.com/twy100143x32x15.htm",
  },
  {
    singer: "初音ミク",
    composer: "ぽわぽわP",
    title: "アストロノーツ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/16410.html",
  },
  {
    singer: "GUMI",
    composer: "黒髪ストロングP",
    title: "林檎売りの泡沫少女",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/23451.html",
  },
  {
    singer: "AKINO",
    composer: "",
    title: "創聖のアクエリオン",
    lyric_url: "http://www.kasi-time.com/item-4110.html",
  },
  {
    singer: "GUMI",
    composer: "buzzG",
    title: "Fairytale,",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/22456.html",
  },
  {
    singer: "巡音ルカ(ENG)",
    composer: "baker",
    title: "「ARPK」",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/12047.html",
  },
  {
    singer: "えり～な",
    composer: "",
    title: "「ドキッ！こういうのが恋なの？」",
    lyric_url: "http://miraclestars.seesaa.net/article/175198669.html",
  },
  {
    singer: "GUMI V3(English)",
    composer: "Crusher-P",
    title: "ECHO",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/30536.html",
  },
  {
    singer: "初音ミク",
    composer: "ぽわぽわP",
    title: "ストロボライト",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/18115.html",
  },
  {
    singer: "初音ミク",
    composer: "のぼる↑P",
    title: "モノクロ∞ブルースカイ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/9343.html",
  },
  {
    singer: "初音ミク",
    composer: "40㍍P",
    title: "トリノコシティ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/11134.html",
  },
  {
    singer: "v flower",
    composer: "バルーン",
    title: "花瓶に触れた",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/33996.html",
  },
  {
    singer: "初音ミクAppend",
    composer: "トーマ",
    title: "オレンジ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/23837.html",
  },
  {
    singer: "偽物語",
    composer: "",
    title: "白金ディスコ-Acoustic ver.-",
    lyric_url: "http://www.nicovideo.jp/watch/sm17331117",
  },
  {
    singer: "東京事変",
    composer: "",
    title: "遭難",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B07841",
  },
  {
    singer: "鏡音リン",
    composer: "ライブP",
    title: "S・K・Y",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/9949.html",
  },
  {
    singer: "初音ミク",
    composer: "40㍍P",
    title: "空中アクアリウム",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/10595.html",
  },
  {
    singer: "Crispy脆樂團",
    composer: "",
    title: "100分",
    lyric_url: "https://mojim.com/twy113323x1x4.htm",
  },
  {
    singer: "河仁傑",
    composer: "",
    title: "喜歡討厭你 feat.江松霖",
    lyric_url: "https://www.youtube.com/watch?v=-wU92CaRRjw",
  },
  {
    singer: "林宥嘉",
    composer: "",
    title: "兜圈",
    lyric_url: "https://mojim.com/twy105350x16x1.htm",
  },
  {
    singer: "巡音ルカ",
    composer: "ジミーサムP",
    title: "No Logic",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/6558.html",
  },
  {
    singer: "江美琪",
    composer: "",
    title: "雙手的溫柔",
    lyric_url: "https://mojim.com/twy100030x3x3.htm",
  },
  {
    singer: "初音ミク",
    composer: "電ポルP",
    title: "サイノウサンプラー Acoustic ver.",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/13167.html",
  },
  {
    singer: "GUMI",
    composer: "ささくれP",
    title: "カムパネルラ Piano ver.",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/7035.html",
  },
  {
    singer: "藤木直人",
    composer: "",
    title: "サンクフル☆エブリナイ",
    lyric_url: "http://www.kasi-time.com/item-19943.html",
  },
  {
    singer: "氣志團",
    composer: "",
    title: "One Night Carnival",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=66593",
  },
  {
    singer: "太妍",
    composer: "",
    title: "I",
    lyric_url: "http://oops60213.pixnet.net/blog/post/437510335-taeyeon---i-feat.verbal-jint-%E4%B8%AD%E9%9F%93%E6%AD%8C%E8%A9%9E",
  },
  {
    singer: "南方四賤客",
    composer: "",
    title: "聖誕特集陀螺歌",
    lyric_url: "http://vlog.xuite.net/play/ZDlUWGV0LTM0MTA2MjEuZmx2/%E5%8D%97%E6%96%B9%E5%9B%9B%E8%B3%A4%E5%AE%A2-%E8%81%96%E8%AA%95%E7%89%B9%E9%9B%86%E9%99%80%E8%9E%BA%E6%AD%8C",
  },
  {
    singer: "Spangle call Lilli line",
    composer: "",
    title: "veek",
    lyric_url: "https://aslyrics.wordpress.com/lyrics/spangle-call-lilli-line/nanae-kanji/",
  },
  {
    singer: "aiko",
    composer: "",
    title: "スター",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B12251",
  },
  {
    singer: "騎去哪",
    composer: "",
    title: "吸到煙就罵幹",
    lyric_url: "https://www.youtube.com/watch?v=-P_ijntWKA8",
  },
  {
    singer: "JUJU",
    composer: "",
    title: "ナツノハナ",
    lyric_url: "http://www.kasi-time.com/item-14861.html",
  },
  {
    singer: "Asian kung-fu generation",
    composer: "",
    title: "君という花",
    lyric_url: "http://www.ufret.jp/song.php?data=2251",
  },
  {
    singer: "相対性理論",
    composer: "",
    title: "チャイナアドバイス",
    lyric_url: "http://www.ufret.jp/song.php?data=9728",
  },
  {
    singer: "相対性理論",
    composer: "",
    title: "(恋は)百年戦争",
    lyric_url: "j-lyric.net/artist/a04f804/l02012a.html",
  },
  {
    singer: "初音ミク",
    composer: "ねこぼーろ/ササノマリイ sasanomaly",
    title: "てのひらワンダーランド",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/31812.html",
  },
  {
    singer: "初音ミク",
    composer: "ねこぼーろ/ササノマリイ sasanomaly",
    title: "共感覚おばけ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/32040.html",
  },
  {
    singer: "初音ミク",
    composer: "ねこぼーろ/ササノマリイ sasanomaly",
    title: "きかせたいのは",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/32149.html",
  },
  {
    singer: "初音ミクAppend",
    composer: "みきとP",
    title: "刹那プラス",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/21661.html",
  },
  {
    singer: "中島美嘉",
    composer: "",
    title: "雪の華",
    lyric_url: "https://mojim.com/twy102241x16x9.htm",
  },
  {
    singer: "莫文蔚",
    composer: "",
    title: "愛情",
    lyric_url: "https://mojim.com/twy100098x22x4.htm",
  },
  {
    singer: "GUMI",
    composer: "もじゃ",
    title: "ドナーソング",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/25058.html",
  },
  {
    singer: "東京事変",
    composer: "",
    title: "スーパースター",
    lyric_url: "http://www.utamap.com/showkasi.php?surl=B13007",
  },
  {
    singer: "GUMI",
    composer: "西沢さんP",
    title: "アセロラ",
    lyric_url: "http://www5.atwiki.jp/hmiku/pages/34184.html",
  },
  {
    singer: "尹美萊 (太陽的後裔 OST)",
    composer: "",
    title: "Always",
    lyric_url: "https://goo.gl/TdbSi8",
  },
  {
    singer: "初音ミク",
    composer: "ナブナ",
    title: "夜明けと蛍",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/30746.html",
  },
  {
    singer: "GUMI",
    composer: "もじゃ / 大柴広己",
    title: "さよならミッドナイト",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/18805.html",
  },
  {
    singer: "",
    composer: "",
    title: "為忙碌人製作的「大嘴鳥」",
    lyric_url: "https://www.youtube.com/watch?v=NNxEg8IJZhg",
  },
  {
    singer: "萬能青年旅店",
    composer: "",
    title: "殺死那個石家莊人",
    lyric_url: "https://mojim.com/twy109920x1x9.htm",
  },
  {
    singer: "馬頔",
    composer: "",
    title: "南山南",
    lyric_url: "https://mojim.com/twy142762x1x3.htm",
  },
  {
    singer: "Lily Chou-Chou",
    composer: "",
    title: "飛べない翼",
    lyric_url: "http://petitlyrics.com/lyrics/139049",
  },
  {
    singer: "Lily Chou Chou",
    composer: "",
    title: "空虚な石 / 共鳴",
    lyric_url: "http://petitlyrics.com/lyrics/139056",
  },
  {
    singer: "あさきのくりむ童話",
    composer: "",
    title: "去る金合戦",
    lyric_url: "https://www7.atwiki.jp/bemanilyrics/pages/1791.html",
  },
  {
    singer: "初音ミク",
    composer: "ピノキオP",
    title: "マッシュルームマザー",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/17718.html",
  },
  {
    singer: "徐佳瑩",
    composer: "",
    title: "你敢不敢",
    lyric_url: "https://mojim.com/twy105599x7x3.htm",
  },
  {
    singer: "Cicada",
    composer: "",
    title: "以一種假裝放蕩的矜持與你告別",
    lyric_url: "https://www.youtube.com/watch?v=KU28BTLeonQ",
  },
  {
    singer: "pg.lost",
    composer: "",
    title: "Yes I Am",
    lyric_url: "https://www.youtube.com/watch?v=C1XIa8IjN8o",
  },
  {
    singer: "太妍 / TAEYEON / 태연",
    composer: "",
    title: "11:11",
    lyric_url: "https://goo.gl/U2RfvS",
  },
  {
    singer: "初音ミク",
    composer: "瀬名航",
    title: "めんどくさいや",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/31595.html",
  },
  {
    singer: "初音ミク",
    composer: "ピノキオP",
    title: "きみも悪い人でよかった",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/34989.html",
  },
  {
    singer: "初音ミク",
    composer: "コウ",
    title: "ネアの幻遊",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/34984.html",
  },
  {
    singer: "結月ゆかり",
    composer: "黒澤まどか",
    title: "鳳仙花",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/28897.html",
  },
  {
    singer: "初音ミク",
    composer: "ぽわぽわP",
    title: "うたをうたうひと",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/22153.html",
  },
  {
    singer: "GUMI",
    composer: "ナポリP",
    title: "不完全な処遇",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/30985.html",
  },
  {
    singer: "李千娜",
    composer: "",
    title: "心花開",
    lyric_url: "https://mojim.com/twy109601x2x2.htm",
  },
  {
    singer: "渋谷毅",
    composer: "告白 Confession Original Soundtrack",
    title: "Milk",
    lyric_url: "http://www.autolyric.com/zh-hant/lyric/129719",
  },
  {
    singer: "BECK",
    composer: "",
    title: "I've got a feeling",
    lyric_url: "www.songlyrics.com/beck/i-ve-got-a-feeling-lyrics/",
  },
  {
    singer: "BECK",
    composer: "",
    title: "Follow me",
    lyric_url: "www.metrolyrics.com/follow-me-lyrics-beck.html",
  },
  {
    singer: "朴樹",
    composer: "",
    title: "平凡之路",
    lyric_url: "https://www.youtube.com/watch?v=NjTT5_RSkw4",
  },
  {
    singer: "逃跑计划Escape Plan",
    composer: "",
    title: "夜空中最亮的星",
    lyric_url: "https://www.youtube.com/watch?v=fzuy63eCUKc",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "稻香",
    lyric_url: "http://mojim.com/twy100951x27x11.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "七里香",
    lyric_url: "https://mojim.com/twy100951x9x2.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "愛在西元前",
    lyric_url: "https://mojim.com/twy100951x2x1.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "半島鐵盒",
    lyric_url: "https://mojim.com/twy100951x5x2.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "黑色幽默",
    lyric_url: "https://mojim.com/twy100951x1x6.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "龍捲風",
    lyric_url: "https://mojim.com/twy100951x1x9.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "爺爺泡的茶",
    lyric_url: "https://mojim.com/twy100951x5x7.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "上海一九四三",
    lyric_url: "https://mojim.com/twy100951x6x16.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "晴天",
    lyric_url: "https://mojim.com/twy100951x7x3.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "星晴",
    lyric_url: "mojim.com/twy100951x6x14.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "簡單愛",
    lyric_url: "https://mojim.com/twy100951x10x20.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "安靜",
    lyric_url: "https://mojim.com/twy100951x6x10.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "開不了口",
    lyric_url: "https://mojim.com/twy100951x2x5.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "彩虹",
    lyric_url: "https://mojim.com/twy100951x22x2.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "夜曲",
    lyric_url: "https://mojim.com/twy100951x17x1.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "可愛女人",
    lyric_url: "https://mojim.com/twy100951x1x1.htm",
  },
  {
    singer: "周杰倫",
    composer: "",
    title: "給我一首歌的時間",
    lyric_url: "mojim.com/twy100951x27x2.htm",
  },
  {
    singer: "陶喆",
    composer: "",
    title: "黑色柳丁",
    lyric_url: "mojim.com/twy100207x4x1.htm",
  },
  {
    singer: "陶喆",
    composer: "",
    title: "小鎮姑娘",
    lyric_url: "https://mojim.com/twy100207x3x8.htm",
  },
  {
    singer: "陶喆",
    composer: "",
    title: "愛我還是他",
    lyric_url: "https://mojim.com/twy100207x7x6.htm",
  },
  {
    singer: "whoo × ちょまいよ",
    composer: "",
    title: "ワルツ / Waltz﻿",
    lyric_url: "https://www.youtube.com/watch?v=QtzEGdIHKnQ",
  },
  {
    singer: "相対性理論",
    composer: "",
    title: "四角革命",
    lyric_url: "https://mojim.com/twy108354x4x4.htm",
  },
  {
    singer: "相対性理論",
    composer: "",
    title: "学級崩壊",
    lyric_url: "https://mojim.com/twy108354x4x6.htm",
  },
  {
    singer: "相対性理論",
    composer: "",
    title: "ミス・パラレルワールド",
    lyric_url: "j-lyric.net/artist/a04f804/l020127.html",
  },
  {
    singer: "相対性理論",
    composer: "",
    title: "気になるあの娘",
    lyric_url: "j-lyric.net/artist/a04f804/l02012e.html",
  },
  {
    singer: "相対性理論",
    composer: "",
    title: "小学館",
    lyric_url: "j-lyric.net/artist/a04f804/l02012f.html",
  },
  {
    singer: "フジファブリック",
    composer: "",
    title: "若者のすべて",
    lyric_url: "www.utamap.com/showkasi.php?surl=B25719",
  },
  {
    singer: "草東沒有派對",
    composer: "",
    title: "山海",
    lyric_url: "https://mojim.com/twy163395x1x10.htm",
  },
  {
    singer: "草東沒有派對",
    composer: "",
    title: "大風吹",
    lyric_url: "https://mojim.com/twy163395x1x5.htm",
  },
  {
    singer: "草東沒有派對",
    composer: "",
    title: "爛泥",
    lyric_url: "https://www.youtube.com/watch?v=xbmCcFOUcsM",
  },
  {
    singer: "草東沒有派對",
    composer: "",
    title: "醜",
    lyric_url: "https://www.youtube.com/watch?v=uOwENjZRa4w",
  },
  {
    singer: "宇多田ヒカル",
    composer: "",
    title: "Goodbye Happiness",
    lyric_url: "www.kasi-time.com/item-51225.html",
  },
  {
    singer: "阿肆",
    composer: "",
    title: "預謀邂逅",
    lyric_url: "https://mojim.com/twy120519x1x3.htm",
  },
  {
    singer: "阿肆",
    composer: "",
    title: "我在人民廣場吃炸雞",
    lyric_url: "https://mojim.com/twy120519x1x7.htm",
  },
  {
    singer: "蔡健雅",
    composer: "",
    title: "別找我麻煩",
    lyric_url: "https://mojim.com/twy100166x19x6.htm",
  },
  {
    singer: "Mandy",
    composer: "Mr.Bartender 第三季 ED",
    title: "灼火",
    lyric_url: "https://www.ptt.cc/bbs/popmusic/M.1474016659.A.382.html",
  },
  {
    singer: "ハンバートハンバート",
    composer: "",
    title: "罪の味",
    lyric_url: "j-lyric.net/artist/a0548cb/l0232d2.html",
  },
  {
    singer: "星野源",
    composer: "",
    title: "フィルム",
    lyric_url: "www.kasi-time.com/item-59195.html",
  },
  {
    singer: "星野源",
    composer: "",
    title: "老夫婦",
    lyric_url: "https://mojim.com/twy110255x5x7.htm",
  },
  {
    singer: "サカナクション",
    composer: "",
    title: "新宝島",
    lyric_url: "j-lyric.net/artist/a04d6c9/l037b92.html",
  },
  {
    singer: "サカナクション",
    composer: "",
    title: "ミュージック",
    lyric_url: "j-lyric.net/artist/a04d6c9/l02b7d3.html",
  },
  {
    singer: "サカナクション",
    composer: "",
    title: "僕と花",
    lyric_url: "https://mojim.com/tw108127x7.htm",
  },
  {
    singer: "フジファブリック",
    composer: "",
    title: "Anthem",
    lyric_url: "j-lyric.net/artist/a033e7f/l01847d.html",
  },
  {
    singer: "フジファブリック",
    composer: "",
    title: "赤黄色の金木犀",
    lyric_url: "https://mojim.com/twy108819x18x1.htm",
  },
  {
    singer: "椎名林檎",
    composer: "",
    title: "歌舞伎町の女王",
    lyric_url: "www.utamap.com/showkasi.php?surl=65566",
  },
  {
    singer: "椎名林檎",
    composer: "",
    title: "17",
    lyric_url: "http://mojim.com/twy100613x13x10.htm",
  },
  {
    singer: "椎名林檎",
    composer: "",
    title: "茎(STEM)",
    lyric_url: "https://mojim.com/twy100613x5x5.htm",
  },
  {
    singer: "椎名林檎 × 斉藤ネコ",
    composer: "",
    title: "ハツコイ娼女",
    lyric_url: "www.utamap.com/showkasi.php?surl=B20990",
  },
  {
    singer: "椎名林檎 × 斉藤ネコ",
    composer: "",
    title: "意識 consciously",
    lyric_url: "j-lyric.net/artist/a00450a/l001c75.html",
  },
  {
    singer: "amazarashi",
    composer: "",
    title: "季節は次々死んでいく",
    lyric_url: "www.kasi-time.com/item-75108.html",
  },
  {
    singer: "GUMI",
    composer: "赤髪",
    title: "StarCrew",
    lyric_url: "https://www5.atwiki.jp/hmiku/pages/20453.html",
  }
]
song.map! do |s|
  s[:singer]   = Singer.find_by_name(s[:singer])
  s[:composer] = Singer.find_by_name(s[:composer])
  s
end
Song.create!(song)
