# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

song_info = [
  { content: "消音" },
  { content: "消音結束" },
]
Songinfo.create!(song_info)

song = [
  [ "宋冬野", "", "夢遺少年", "https://mojim.com/twy120593x1x6.htm" ],
  [ "徐佳瑩", "", "不怕慶祝", "https://mojim.com/twy105599x7x4.htm" ],
  [ "徐佳瑩", "", "失落沙洲", "https://mojim.com/twy105599x15x10.htm" ],
  [ "徐佳瑩", "", "身騎白馬", "https://mojim.com/twy105599x15x25.htm" ],
  [ "蔡健雅", "", "雙棲動物", "https://mojim.com/twy100166x10x1.htm" ],
  [ "蔡健雅", "", "無底洞", "https://mojim.com/twy100166x8x2.htm" ],
  [ "蔡健雅", "", "陌生人", "https://mojim.com/tw100166x8.htm#6" ],
  [ "蔡健雅", "", "記念", "https://mojim.com/twy100166x3x2.htm" ],
  [ "蔡健雅", "", "思念", "https://mojim.com/twy100166x13x7.htm" ],
  [ "解偉苓", "", "放逐愛情", "https://mojim.com/twy106559x11x4.htm" ],
  [ "徐佳瑩", "", "明天的事情", "https://mojim.com/twy105599x11x2.htm" ],
  [ "梁詠琪", "", "膽小鬼", "https://mojim.com/twy100093x4x2.htm" ],
  [ "梁詠琪", "", "Amour", "https://mojim.com/twy100093x15x2.htm" ],
  [ "anNina", "", "対象a", "http://www.kasi-time.com/item-15783.html" ],
  [ "荒井由実", "", "やさしさに包まれたなら", "http://www.nicovideo.jp/watch/sm16983161?ref=search_key_video" ],
  [ "へっぽこ六弦使い", "", "風になる-Acoustic ver.-", "http://www.nicovideo.jp/watch/sm16899289" ],
  [ "FREENOTE", "", "ラストワルツ", "https://mojim.com/twy107777x2x3.htm" ],
  [ "偽物語&吉幾三", "", "白金ディスコ", "http://www.nicovideo.jp/watch/sm17321142?playlist_type=mylist&group_id=25063698&mylist_sort=1&ref=my_mylist_s1_p1_n74" ],
  [ "初音ミク", "keeno", "crack", "http://www5.atwiki.jp/hmiku/pages/12661.html" ],
  [ "初音ミク", "keeno", "alternate", "http://www5.atwiki.jp/hmiku/pages/32950.html" ],
  [ "初音ミク", "keeno", "glow", "http://www5.atwiki.jp/hmiku/pages/10599.html" ],
  [ "初音ミク", "keeno", "longing", "http://www5.atwiki.jp/hmiku/pages/13759.html" ],
  [ "楊乃文", "", "星星堆滿天", "https://mojim.com/twy100142x5x3.htm" ],
  [ "楊乃文", "", "女爵", "https://mojim.com/twy100142x6x1.htm" ],
  [ "陳綺貞", "", "太陽(immortal)", "https://mojim.com/twy100115x21x3.htm" ],
  [ "陳綺貞", "", "距離(distance)", "https://mojim.com/twy100115x21x5.htm" ],
  [ "陳綺貞", "", "魚(the edge)", "https://mojim.com/twy100115x21x4.htm" ],
  [ "陳綺貞", "", "下個星期去英國(go to England next week)", "https://mojim.com/twy100115x21x8.htm" ],
  [ "陳綺貞", "", "我親愛的偏執狂", "https://mojim.com/twy100115x6x1.htm" ],
  [ "陳綺貞", "", "太聰明", "https://mojim.com/twy100115x6x2.htm" ],
  [ "陳綺貞", "", "小步舞曲", "https://mojim.com/twy100115x6x3.htm" ],
  [ "陳綺貞", "", "1234567", "https://mojim.com/twy100115x6x4.htm" ],
  [ "陳綺貞", "", "躺在你的衣櫃", "https://mojim.com/twy100115x6x6.htm" ],
  [ "陳綺貞", "", "吉他手", "https://mojim.com/twy100115x6x8.htm" ],
  [ "陳綺貞", "", "黑眼圈", "https://mojim.com/twy100115x6x9.htm" ],
  [ "陳綺貞", "", "小小校歌", "https://mojim.com/twy100115x11x2.htm" ],
  [ "陳綺貞", "", "天天想你", "https://mojim.com/twy100115x23x22.htm" ],
  [ "梁靜茹", "", "可惜不是你", "https://mojim.com/twy100095x12x6.htm" ],
  [ "米津玄師", "", "アイネクライネ", "http://j-lyric.net/artist/a0579b7/l031237.html" ],
  [ "米津玄師", "", "メランコリーキッチン", "http://j-lyric.net/artist/a0579b7/l031238.html" ],
  [ "米津玄師", "", "vivi", "http://j-lyric.net/artist/a0579b7/l02f9fb.html" ],
  [ "梁靜茹", "", "beautiful", "https://mojim.com/twy100095x7x1.htm" ],
  [ "初音ミク", "ジミーサムP", "Calc.", "http://www5.atwiki.jp/hmiku/pages/11898.html" ],
  [ "初音ミク", "におP", "Tómur", "http://www5.atwiki.jp/hmiku/pages/13140.html" ],
  [ "GUMI", "baker", "違う空", "http://www5.atwiki.jp/hmiku/pages/6980.html" ],
  [ "土岐麻子", "sasakure.UK", "深海のリトルクライ", "http://ameblo.jp/gannpurayakidaisuki/entry-11540863429.html" ],
  [ "光GENJI", "", "勇気100%", "http://www.nicovideo.jp/watch/sm15535417" ],
  [ "鏡音レン", "DATEKEN", "なまえのないうた", "http://www5.atwiki.jp/hmiku/pages/6256.html" ],
  [ "巡音ルカ", "sasakure.UK", "ワンダーラスト", "http://www5.atwiki.jp/hmiku/pages/4137.html" ],
  [ "GUMI", "ささくれP", "ぼくらの16Bit戦争", "http://www5.atwiki.jp/hmiku/pages/5869.html" ],
  [ "初音ミク", "宮沢もよよ", "植物園", "http://www5.atwiki.jp/hmiku/pages/22256.html" ],
  [ "初音ミク", "ATOLS", "ブレス", "http://www5.atwiki.jp/hmiku/pages/11455.html" ],
  [ "初音ミク", "青木月光", "夢と葉桜", "http://www5.atwiki.jp/hmiku/pages/17261.html" ],
  [ "初音ミク", "すこっぷ", "ドミノ倒シ", "http://www5.atwiki.jp/hmiku/pages/13999.html" ],
  [ "清浦夏実", "", "旅の途中", "http://www.kasi-time.com/item-28561.html" ],
  [ "東京事変", "", "修羅場", "http://www.nicovideo.jp/watch/sm17115246" ],
  [ "初音ミクAppend", "ねこぼーろ/ササノマリイ sasanomaly", "戯言スピーカー", "http://www5.atwiki.jp/hmiku/pages/15786.html" ],
  [ "初音ミクAppend", "ピノキオP", "ありふれたせかいせいふく", "http://www5.atwiki.jp/hmiku/pages/21984.html" ],
  [ "初音ミク", "ハチ", "clock lock works", "http://www5.atwiki.jp/hmiku/pages/7433.html" ],
  [ "小南泰葉", "", "HOME", "https://mojim.com/twy110713x2x5.htm" ],
  [ "小南泰葉", "", "Trash", "http://www.kasi-time.com/item-63542.html" ],
  [ "GUMI", "蝶々P", "心做し", "http://www5.atwiki.jp/hmiku/pages/28057.html" ],
  [ "Lucy Rose", "", "Shiver", "http://www.azlyrics.com/lyrics/lucyrose/shiver.html" ],
  [ "初音ミク", "電ポルP", "サイノウサンプラー", "http://www5.atwiki.jp/hmiku/pages/13167.html" ],
  [ "石川智晶", "", "アンインストール", "http://www.kasi-time.com/item-8852.html" ],
  [ "GUMI", "40㍍P", "シリョクケンサ", "http://www5.atwiki.jp/hmiku/pages/17600.html" ],
  [ "初音ミク", "ハチ", "WORLD'S END UMBRELLA", "http://www5.atwiki.jp/hmiku/pages/8608.html" ],
  [ "初音ミク", "ほえほえP", "うたうたいのうた", "http://www5.atwiki.jp/hmiku/pages/13620.html" ],
  [ "初音ミク", "ぽわぽわP", "ストロボラスト", "http://www5.atwiki.jp/hmiku/pages/14092.html" ],
  [ "初音ミク", "ジミーサムP", "Little Traveler", "http://www5.atwiki.jp/hmiku/pages/3355.html" ],
  [ "Aiko", "", "カブトムシ", "http://j-lyric.net/artist/a000619/l00091e.html" ],
  [ "Tizzy Bac", "", "我不小心", "https://mojim.com/twy102598x3x2.htm" ],
  [ "Tizzy Bac", "", "我又再度依戀上昨天", "https://mojim.com/twy102598x3x5.htm" ],
  [ "Tizzy Bac", "", "You'll See", "https://mojim.com/twy102598x3x13.htm" ],
  [ "陳綺貞", "", "鞋貓夫人，Madame!!!", "https://mojim.com/twy102598x3x12.htm" ],
  [ "Tizzy Bac", "", "季後賽", "https://mojim.com/twy102598x3x2.htm" ],
  [ "Tizzy Bac", "", "瞬間白眼一千遍", "https://mojim.com/twy102598x6x11.htm" ],
  [ "Tizzy Bac", "", "太陽快跑", "https://mojim.com/twy102598x6x13.htm" ],
  [ "Tizzy Bac", "", "For the Way I Live", "https://mojim.com/twy102598x3x2.htm" ],
  [ "Tizzy Bac", "", "鐵之貝克", "https://mojim.com/twy102598x6x1.htm" ],
  [ "初音ミク", "とあ", "ツギハギスタッカート", "http://www5.atwiki.jp/hmiku/pages/29529.html" ],
  [ "東森幼幼", "", "卡加布列島", "https://www.youtube.com/watch?v=9DeBAD_HDBY" ],
  [ "茶太", "", "だんご大家族", "http://www.nicovideo.jp/watch/sm13697302" ],
  [ "IA", "じん/自然の敵P", "アヤノの幸福理論", "http://www5.atwiki.jp/hmiku/pages/25204.html" ],
  [ "Loco Roco", "", "ロコロコのうた", "http://www.uta-net.com/song/46763/" ],
  [ "初音ミク", "ATOLS", "マカロン", "http://www5.atwiki.jp/hmiku/pages/22485.html" ],
  [ "張震嶽", "", "再見", "https://mojim.com/twy100091x17x7.htm" ],
  [ "魏如昀", "", "聽見下雨的聲音", "https://mojim.com/twy105804x4x1.htm" ],
  [ "蔡健雅", "", "若你碰到他", "https://mojim.com/twy100166x16x8.htm" ],
  [ "Taylor Swift", "", "Red", "https://mojim.com/twy105095x13x2.htm" ],
  [ "莫文蔚", "", "If", "https://mojim.com/tw100098x29.htm" ],
  [ "羊毛とおはな", "", "Englishman In New York", "http://www.uta-net.com/song/174360/" ],
  [ "陶喆", "", "寂寞的季節", "https://mojim.com/twy100207x6x14.htm" ],
  [ "張惠妹", "", "偏執面", "https://mojim.com/twy100090x45x5.htm" ],
  [ "張惠妹", "", "三月", "https://mojim.com/twy100090x45x3.htm" ],
  [ "張惠妹", "", "真實", "https://mojim.com/twy100090x18x4.htm" ],
  [ "張惠妹", "", "人質", "https://mojim.com/twy100090x27x2.htm" ],
  [ "Keno", "", "おはよう", "http://www.kasi-time.com/item-12377.html" ],
  [ "初音ミク", "ほえほえP", "文学少年の憂鬱", "http://www5.atwiki.jp/hmiku/pages/8153.html" ],
  [ "初音ミク", "ねこぼーろ/ササノマリイ sasanomaly", "オノマトペメガネ", "http://www5.atwiki.jp/hmiku/pages/30477.html" ],
  [ "初音ミク", "すこっぷ", "アイロニ", "http://www5.atwiki.jp/hmiku/pages/21743.html" ],
  [ "きゃりーぱみゅぱみゅ", "", "CANDY CANDY", "http://j-lyric.net/artist/a055611/l0282b3.html" ],
  [ "きゃりーぱみゅぱみゅ", "", "PONPONPON", "http://www.nicovideo.jp/watch/sm16388459" ],
  [ "初音ミク", "におP", "rain stops, good-bye", "http://www5.atwiki.jp/hmiku/pages/1889.html" ],
  [ "初音ミク", "古川本舗", "Alice", "http://www5.atwiki.jp/hmiku/pages/6132.html" ],
  [ "Radwimps", "", "me me she", "http://j-lyric.net/artist/a04ac97/l009860.html" ],
  [ "初音ミク", "Paolino", "キミトセカイ", "http://www5.atwiki.jp/hmiku/pages/15739.html" ],
  [ "初音ミクAppend", "フェイP", "Souvenir", "http://www5.atwiki.jp/hmiku/pages/18392.html" ],
  [ "ZONE", "", "secret base～君がくれたもの～", "http://www.utamap.com/showkasi.php?surl=66287" ],
  [ "高橋洋子", "", "残酷な天使のテーゼ", "http://www.utamap.com/showkasi.php?surl=58075" ],
  [ "初音ミク", "DECO*27", "恋距離遠愛", "http://www5.atwiki.jp/hmiku/pages/4250.html" ],
  [ "GUMI", "DECO*27", "弱虫モンブラン", "http://www5.atwiki.jp/hmiku/pages/9644.html" ],
  [ "初音ミクAppend", "ねこぼーろ/ササノマリイ sasanomaly", "自傷無色", "http://www5.atwiki.jp/hmiku/pages/24287.html" ],
  [ "妖怪ウォッチ", "", "ようかい体操第一", "http://www.kasi-time.com/item-71629.html" ],
  [ "鄧紫棋", "", "A.I.N.Y", "https://mojim.com/twy105703x5x2.htm" ],
  [ "A-lin", "", "給我一個理由忘記", "https://mojim.com/twy104821x5x2.htm" ],
  [ "Sia", "", "Chandelier", "http://www.lyricsfreak.com/s/sia/chandelier_21079675.html" ],
  [ "東京事変", "", "能動的三分間", "http://www.utamap.com/showkasi.php?surl=Z00073" ],
  [ "千石撫子", "花澤香菜", "恋爱サーキュレーション", "http://www.kasi-time.com/item-46321.html" ],
  [ "椎名林檎", "", "長く短い祭", "http://kashinavi.com/song_view.html?88670" ],
  [ "初音ミク", "古川本舗", "グリグリメガネと月光蟲", "http://www5.atwiki.jp/hmiku/pages/9870.html" ],
  [ "初音ミク", "古川本舗", "girlfriend", "http://www5.atwiki.jp/hmiku/pages/7557.html" ],
  [ "Do As Infinity", "", "遠雷", "https://mojim.com/twy100695x6x6.htm" ],
  [ "洪佩瑜", "", "踮起腳尖愛", "https://mojim.com/twy109442x12x3.htm" ],
  [ "林嘉欣", "", "女明星", "https://mojim.com/twy100060x4x6.htm" ],
  [ "鄭秀文", "", "808", "https://mojim.com/twy100170x64x25.htm" ],
  [ "許慧欣", "", "愛情抗體", "https://mojim.com/twy102128x5x7.htm" ],
  [ "孫燕姿", "", "綠光", "https://mojim.com/twy100663x19x56.htm" ],
  [ "蘇慧倫", "", "鴨子", "https://mojim.com/tw100185x3.htm" ],
  [ "阿杜&江蕙", "", "夢中的情話", "https://mojim.com/twy100229x23x2.htm" ],
  [ "江蕙", "", "家後", "https://mojim.com/twy100229x51x30.htm" ],
  [ "張秀卿", "", "車站", "https://mojim.com/twy100086x8x11.htm" ],
  [ "五月天", "", "心中無別人", "https://mojim.com/twy100012x2x4.htm" ],
  [ "五月天", "", "雨眠", "https://mojim.com/twy100012x2x8.htm" ],
  [ "五月天", "", "溫柔", "https://mojim.com/twy100012x2x10.htm" ],
  [ "五月天", "", "憨人", "https://mojim.com/twy100012x2x6.htm" ],
  [ "五月天", "", "借問眾神明", "https://mojim.com/twy100012x21x28.htm" ],
  [ "五月天", "", "一顆蘋果", "https://mojim.com/twy100012x19x16.htm" ],
  [ "五月天", "", "時光機", "https://mojim.com/tw100012x13.htm" ],
  [ "五月天", "", "垃圾車", "https://mojim.com/twy100012x21x23.htm" ],
  [ "五月天", "", "好不好", "https://mojim.com/twy100012x21x20.htm" ],
  [ "五月天", "", "I Love You 無望", "https://mojim.com/twy100012x21x26.htm" ],
  [ "劉若英", "", "聽！是誰在唱歌", "https://mojim.com/twy100158x21x12.htm" ],
  [ "GUMI", "ささくれP", "カムパネルラ", "http://www5.atwiki.jp/hmiku/pages/7035.html" ],
  [ "盧廣仲", "", "100種生活", "https://mojim.com/tw105044x4.htm" ],
  [ "萬能青年旅店", "", "秦皇島", "https://mojim.com/twy109920x1x6.htm" ],
  [ "Hello Nico", "", "你是被抹去的那一段風景", "https://mojim.com/cny133635x2x2.htm" ],
  [ "初音ミク", "古川本舗", "mugs", "http://www5.atwiki.jp/hmiku/pages/9682.html" ],
  [ "GUMI", "baker", "羽", "http://www5.atwiki.jp/hmiku/pages/6963.html" ],
  [ "歌愛ユキ", "想太", "またあした", "http://www5.atwiki.jp/hmiku/pages/23142.html" ],
  [ "miki", "古川本舗", "スーパー・ノヴァ", "http://www5.atwiki.jp/hmiku/pages/7833.html" ],
  [ "魏如萱", "", "買你", "https://mojim.com/twy105272x2x4.htm" ],
  [ "陳綺貞", "", "每天都是一種練習", "https://mojim.com/twy100115x19x6.htm" ],
  [ "初音ミク", "古川本舗", "月光食堂", "http://www5.atwiki.jp/hmiku/pages/12449.html" ],
  [ "まふまふ", "", "鏡花水月", "https://www.youtube.com/watch?v=FAYXn2urthw" ],
  [ "東京事変", "", "透明人間", "http://www.nicovideo.jp/watch/sm18317828" ],
  [ "CNBLUE", "", "Hey You", "https://tw.answers.yahoo.com/question/index?qid=20120428000015KK08767" ],
  [ "新堀奈夕", "", "君にスマイル", "http://www.utamap.com/showkasi.php?surl=F03256" ],
  [ "蜉蝣", "", "腐った海で溺れかけている僕を救ってくれた君", "http://j-lyric.net/artist/a04ac94/l009b7a.html" ],
  [ "古川本舗", "", "魔法 feat.ちょまいよ", "https://ja.chordwiki.org/wiki/%E9%AD%94%E6%B3%95" ],
  [ "重音テト", "はるふり", "右に曲ガール", "http://www24.atwiki.jp/utauuuta/pages/3228.html" ],
  [ "重音テト", "はるふり", "浮遊感", "http://www24.atwiki.jp/utauuuta/pages/3444.html" ],
  [ "大塚愛", "", "ユメクイ", "http://www.kasi-time.com/item-4353.html" ],
  [ "張惠妹", "", "掉了", "https://mojim.com/twy100090x36x4.htm" ],
  [ "蕭亞軒&胡彥斌", "", "進行式", "https://mojim.com/twy105032x2x11.htm" ],
  [ "Yui", "", "Again", "http://www.kasi-time.com/item-42706.html" ],
  [ "馬渡松子", "", "微笑みの爆弾", "http://www.kasi-time.com/item-32868.html" ],
  [ "小南泰葉", "", "3355411", "https://mojim.com/twy110713x7x1.htm" ],
  [ "張懸", "", "寶貝", "https://mojim.com/twy104870x1x2.htm" ],
  [ "張懸", "", "喜歡", "https://mojim.com/twy104870x3x3.htm" ],
  [ "A-lin", "", "等你", "https://mojim.com/twy110507x7x3.htm" ],
  [ "任賢齊", "", "我是一隻魚", "https://mojim.com/twy100028x25x8.htm" ],
  [ "任賢齊", "", "春天花會開", "https://mojim.com/twy100028x21x4.htm" ],
  [ "陳綺貞", "", "Self", "https://mojim.com/twy100115x15x7.htm" ],
  [ "棉花糖", "", "2375", "https://mojim.com/twy105564x1x2.htm" ],
  [ "初音ミク", "U-ji", "Chip Tears", "http://www5.atwiki.jp/hmiku/pages/2664.html" ],
  [ "初音ミク", "ささくれP", "ナキムシピッポ", "http://www5.atwiki.jp/hmiku/pages/11430.html" ],
  [ "鏡音リン、鏡音レン", "DATEKEN", "紡唄 -つむぎうた-", "http://www5.atwiki.jp/hmiku/pages/4190.html" ],
  [ "初音ミク", "かぴたろう", "恐山ル・ヴォワール", "http://www5.atwiki.jp/hmiku/pages/9276.html" ],
  [ "初音ミク", "40㍍P", "キミボシ", "http://www5.atwiki.jp/hmiku/pages/7116.html" ],
  [ "ハンバート ハンバート", "", "おなじ話", "http://j-lyric.net/artist/a0548cb/l02b996.html" ],
  [ "ハンバート ハンバート", "", "天井", "http://www.utamap.com/showkasi.php?surl=k-130130-063" ],
  [ "ハンバート ハンバート", "", "怪物", "http://j-lyric.net/artist/a0548cb/l02b992.html" ],
  [ "李千娜", "", "愛到站了", "https://mojim.com/twy109601x2x1.htm" ],
  [ "蔡依林", "", "倒帶", "https://mojim.com/twy100163x30x40.htm" ],
  [ "梁靜茹", "", "分手快樂", "https://mojim.com/twy100095x11x24.htm" ],
  [ "南拳媽媽", "", "下雨天", "https://mojim.com/twy104324x7x3.htm" ],
  [ "平井堅", "", "瞳をとじて", "https://mojim.com/twy100977x13x1.htm" ],
  [ "陶晶瑩", "", "那些日子", "https://mojim.com/twy100120x8x5.htm" ],
  [ "GUMI", "10日P", "マーメイド", "http://www5.atwiki.jp/hmiku/pages/15348.html" ],
  [ "原田知世", "", "くちなしの丘", "http://www.utamap.com/showkasi.php?surl=B26170" ],
  [ "Keira Knightley", "", "Lost Stars", "http://www.lyriczz.com/lyrics/keira-knightley/229609-lost-stars/" ],
  [ "初音ミク", "ゆうゆ", "深海少女", "http://www5.atwiki.jp/hmiku/pages/11774.html" ],
  [ "初音ミク", "19's Sound Factory", "Dear", "http://www5.atwiki.jp/hmiku/pages/645.html" ],
  [ "巡音ルカ", "Dixie Flatline", "Just Be Friends", "http://www5.atwiki.jp/hmiku/pages/5809.html" ],
  [ "高鈴", "", "愛してる", "http://www.kasi-time.com/item-45592.html" ],
  [ "あんしんパパ", "", "はじめてのチュウ", "http://www.kasi-time.com/item-37901.html" ],
  [ "ドリーミング", "", "アンパンマンのマーチ", "http://www.utamap.com/showkasi.php?surl=E02014" ],
  [ "mao", "", "夢をかなえてドラえもん", "http://www.kasi-time.com/item-11599.html" ],
  [ "工藤真由", "", "ハートキャッチ☆パラダイス！", "http://www.kasi-time.com/item-47104.html" ],
  [ "MAHO堂", "", "おジャ魔女カーニバル!!", "http://www.kasi-time.com/item-4769.html" ],
  [ "TK from 凛として時雨", "", "unravel", "http://www.kasi-time.com/item-72624.html" ],
  [ "TEMPURA KIDZ", "", "One Step", "http://www.kasi-time.com/item-65667.html" ],
  [ "At17", "", "The Best is Yet to Come", "https://mojim.com/twy102377x3x16.htm" ],
  [ "羅美玲", "", "愛一直閃亮", "https://mojim.com/twy102367x2x6.htm" ],
  [ "羅美玲", "", "紅色向日葵", "https://mojim.com/twy102367x2x5.htm" ],
  [ "陳綺貞", "", "讓我想一想", "https://mojim.com/twy100115x1x1.htm" ],
  [ "EGOIST", "", "- Departures ~あなたにおくるアイの歌~", "http://www.kasi-time.com/item-57988.html" ],
  [ "初音ミク", "MARETU", "うみたがり", "http://www.nicovideo.jp/watch/sm26501160" ],
  [ "巡音ルカ", "KEI", "Hello, Worker", "http://www5.atwiki.jp/hmiku/pages/18090.html" ],
  [ "YMCK", "", "Magical 8Bit Tour", "https://mojim.com/twy141591x3x2.htm" ],
  [ "YMCK", "", "夢の中へ", "http://www.kget.jp/lyric/67901/%E5%A4%A2%E3%81%AE%E4%B8%AD%E3%81%B8_YMCK" ],
  [ "孝琳", "", "hello,goodbye", "http://eros90316.pixnet.net/blog/post/55873803-%E2%99%AA%E9%9F%93%E5%8A%87%E3%80%8A%E4%BE%86%E8%87%AA%E6%98%9F%E6%98%9F%E7%9A%84%E4%BD%A0%E3%80%8Bost---%E4%BD%A0%E5%A5%BD%EF%BC%8C%E5%86%8D%E8%A6%8B(%E9%99%84" ],
  [ "DAOKO", "", "水星", "http://j-lyric.net/artist/a059caa/l0352b7.html" ],
  [ "巡音ルカ", "ハチ", "沙上の夢喰い少女", "http://www5.atwiki.jp/hmiku/pages/9873.html" ],
  [ "初音ミク", "kz", "Tell Your World", "http://www5.atwiki.jp/hmiku/pages/19646.html" ],
  [ "椎名林檎", "SPITZ", "スピカ", "https://mojim.com/twy100613x7x3.htm" ],
  [ "椎名林檎", "", "丸の内サディスティック", "http://www.utamap.com/showkasi.php?surl=65571" ],
  [ "らさ", "ハチ", "ニルギリ", "http://www.nicovideo.jp/watch/sm11225397" ],
  [ "初音ミク", "ささくれP", "＊ハロー、プラネット。", "http://www5.atwiki.jp/hmiku/pages/5355.html" ],
  [ "天野月子", "", "箱庭", "http://j-lyric.net/artist/a02411e/l011766.html" ],
  [ "巡音ルカ", "トラボルタP", "トエト", "http://www5.atwiki.jp/hmiku/pages/4316.html" ],
  [ "島みやえい子", "", "奈落の花", "http://www.kasi-time.com/item-15752.html" ],
  [ "初音ミク", "さつき が てんこもり", "お断りします", "http://www5.atwiki.jp/hmiku/pages/10290.html" ],
  [ "初音ミク", "とみー", "1925", "http://www5.atwiki.jp/hmiku/pages/6777.html" ],
  [ "GUMI", "DECO*27", "モザイクロール", "http://www5.atwiki.jp/hmiku/pages/10915.html" ],
  [ "初音ミク", "DECO*27", "二息歩行", "http://www5.atwiki.jp/hmiku/pages/6347.html" ],
  [ "鏡音リン", "iroha", "炉心融解", "http://www5.atwiki.jp/hmiku/pages/3438.html" ],
  [ "GUMI", "40㍍P", "キリトリセン", "http://www5.atwiki.jp/hmiku/pages/14636.html" ],
  [ "初音ミク", "40㍍P", "からくりピエロ", "http://www5.atwiki.jp/hmiku/pages/17230.html" ],
  [ "初音ミク", "黒うさP", "リスキーゲーム", "http://www5.atwiki.jp/hmiku/pages/13873.html" ],
  [ "中島愛", "", "星間飛行", "http://www.nicovideo.jp/watch/sm12152033" ],
  [ "初音ミク", "ナノウ", "ハロ／ハワユ", "http://www5.atwiki.jp/hmiku/pages/10980.html" ],
  [ "supercell", "", "君の知らない物語", "http://www.nicovideo.jp/watch/nm8108292" ],
  [ "やくしまるえつこ", "", "ヴィーナスとジーザス", "http://www.kasi-time.com/item-47983.html" ],
  [ "初音ミク", "えこ。", "トウキョウト・ロック・シティ", "http://www5.atwiki.jp/hmiku/pages/5723.html" ],
  [ "Rie fu", "", "Life is Like a Boat", "http://www.kasi-time.com/item-10944.html" ],
  [ "初音ミク", "KEI", "「アイラビューアイニジュー」", "http://www5.atwiki.jp/hmiku/pages/13834.html" ],
  [ "Double 2 樂團", "", "安全感", "https://www.ptt.cc/bbs/Songs/M.1337593468.A.123.html" ],
  [ "Nylas", "", "廢物曬太陽", "https://mojim.com/twy105980x3x3.htm" ],
  [ "平井堅", "", "大きな古時計", "https://tw.answers.yahoo.com/question/index?qid=20051208000014KK03240" ],
  [ "初音ミク", "kz", "ストロボナイツ", "http://www5.atwiki.jp/hmiku/pages/72.html" ],
  [ "GUMI", "Dios/シグナルP", "会いたい", "http://www5.atwiki.jp/hmiku/pages/11416.html" ],
  [ "レミオロメン", "", "粉雪", "http://j-lyric.net/artist/a000776/l008cf0.html" ],
  [ "kagrra,", "", "うたかた", "http://www.kasi-time.com/item-3565.html" ],
  [ "Supercell", "", "うたかた花火", "http://www.kasi-time.com/item-49570.html" ],
  [ "SNoW", "", "逆さまの蝶", "http://www.kasi-time.com/item-3779.html" ],
  [ "KAITO", "イントロP", "夢懸歌", "http://www5.atwiki.jp/hmiku/pages/10074.html" ],
  [ "手嶌葵", "", "テルーのうた", "http://www.utamap.com/showkasi.php?surl=B17197" ],
  [ "Supercell", "", "夜が明けるよ", "http://www.kasi-time.com/item-52919.html" ],
  [ "古川本舗", "", "グレゴリオ", "http://www.kget.jp/lyric/210337/%E3%82%B0%E3%83%AC%E3%82%B4%E3%83%AA%E3%82%AA_%E5%8F%A4%E5%B7%9D%E6%9C%AC%E8%88%97" ],
  [ "陳綺貞", "", "還是會寂寞", "https://mojim.com/tw100115x14.htm" ],
  [ "井上あずみ", "", "となりのトトロ", "http://www.kasi-time.com/item-10626.html" ],
  [ "氷川きよし", "", "きよしのズンドコ節", "http://www.utamap.com/showkasi.php?surl=52783" ],
  [ "宇多田ヒカル", "", "誰かの願いが叶うころ", "http://www.utamap.com/showkasi.php?surl=B06408" ],
  [ "Hello Nico", "", "接下來如何", "https://mojim.com/cny133635x2x10.htm" ],
  [ "フジファブリック", "", "花", "www.kasi-time.com/item-8331.html" ],
  [ "戴佩妮", "", "你要的爱", "https://mojim.com/twy109442x33x29.htm" ],
  [ "初音ミク", "ぐにょ", "福寿草", "http://www5.atwiki.jp/hmiku/pages/28212.html" ],
  [ "伍佰", "", "夏夜晚風", "https://mojim.com/twy100026x20x19.htm" ],
  [ "Superfly&秦基博", "SPITZ", "楓", "http://www.utamap.com/showkasi.php?surl=64988" ],
  [ "東京事変", "", "落日", "http://www.utamap.com/showkasi.php?surl=B11852" ],
  [ "東京事変", "", "林檎の唄", "http://www.utamap.com/showkasi.php?surl=A00877" ],
  [ "東京事変", "", "閃光少女", "http://www.utamap.com/showkasi.php?surl=A02583" ],
  [ "東京事変", "", "心", "http://j-lyric.net/artist/a000682/l002d98.html" ],
  [ "椎名林檎＆椎名純平", "", "この世の限り", "http://j-lyric.net/artist/a04cb20/l009b46.html" ],
  [ "椎名林檎", "", "茎-STEM", "https://mojim.com/twy100613x5x5.htm" ],
  [ "GUMI", "村人P", "ナキムシロボ", "http://www5.atwiki.jp/hmiku/pages/24099.html" ],
  [ "GUMI", "ノク/Noak", "I love you", "http://www.nicovideo.jp/watch/sm19051857" ],
  [ "初音ミク", "ノク/Noak", "夜とくじら", "http://www.nicovideo.jp/watch/sm26495621" ],
  [ "初音ミク", "ノク/Noak", "8", "http://www5.atwiki.jp/hmiku/pages/34561.html" ],
  [ "紅色リトマス", "", "凛として咲く花の如く", "http://www7.atwiki.jp/bemanilyrics/pages/160.html" ],
  [ "初音ミク", "ジミーサムP", "from Y to Y", "http://www5.atwiki.jp/hmiku/pages/4684.html" ],
  [ "Superfly", "", "愛をこめて花束を", "http://j-lyric.net/artist/a04cdbd/l00c3b4.html" ],
  [ "椎名林檎", "", "ありあまる富", "http://j-lyric.net/artist/a00450a/l017598.html" ],
  [ "ポール・ギルバート", "", "僕の頭", "http://www.nicovideo.jp/watch/sm3631505" ],
  [ "蔡依林", "", "說愛你", "https://mojim.com/twy100163x22x3.htm" ],
  [ "space cake 太空蛋糕", "", "台語歌", "https://www.youtube.com/watch?v=0Jxq10VQwnM" ],
  [ "The Shine & Shine & Shine & Shine 閃閃閃閃", "", "四月物語", "https://www.indievox.com/disc/248" ],
  [ "宋冬野", "", "六層樓", "https://mojim.com/twy120593x1x7.htm" ],
  [ "宋冬野", "", "莉莉安", "https://mojim.com/twy120593x1x2.htm" ],
  [ "宋冬野", "", "斑馬，斑馬", "https://mojim.com/twy120593x1x5.htm" ],
  [ "青森最後の詩人ひろやー", "", "新町", "https://www.youtube.com/watch?v=GHuz-ebtSpU" ],
  [ "初音ミク", "CapsLack", "フェネストラ", "http://www5.atwiki.jp/hmiku/pages/21145.html" ],
  [ "張震嶽", "", "無路用的人", "https://www.youtube.com/watch?v=i5nuDFtGFoc" ],
  [ "フジファブリック", "", "Chocolate Panic", "j-lyric.net/artist/a033e7f/l00c131.html" ],
  [ "フジファブリック", "", "Cheese Burger", "http://www.kasi-time.com/item-16583.html" ],
  [ "My Little Airport", "", "悲傷的採購", "https://mojim.com/twy104690x4x9.htm" ],
  [ "初音ミクAppend", "みきとP", "小夜子", "http://www5.atwiki.jp/hmiku/pages/17663.html" ],
  [ "初音ミク", "古川本舗", "ピアノ・レッスン", "http://www5.atwiki.jp/hmiku/pages/5725.html" ],
  [ "秦基博", "", "Rain", "http://www.kasi-time.com/item-66862.html" ],
  [ "宇多田ヒカル", "", "Be My Last", "http://www.utamap.com/showkasi.php?surl=B11389" ],
  [ "秦基博", "", "ミルクティー", "j-lyric.net/artist/a04c9d1/l00f888.html" ],
  [ "秦基博", "", "鱗", "http://www.utamap.com/showkasi.php?surl=B24567" ],
  [ "初音ミク", "ハチ", "リンネ", "http://www5.atwiki.jp/hmiku/pages/11002.html" ],
  [ "KANA-BOON", "", "ないものねだり", "http://j-lyric.net/artist/a05808c/l02f9ef.html" ],
  [ "Do As Infinity", "", "深い森", "http://www.kasi-time.com/item-4477.html" ],
  [ "Do As Infinity", "", "ROBOT", "http://www.utamap.com/showkasi.php?surl=B08837" ],
  [ "Do As Infinity", "", "楽園", "http://www.kasi-time.com/item-4982.html" ],
  [ "Do As Infinity", "", "柊", "http://www.utamap.com/showkasi.php?surl=B05270" ],
  [ "Do As Infinity", "", "ブランコ", "http://j-lyric.net/artist/a0007b6/l0022ef.html" ],
  [ "Do As Infinity", "", "Yesterday & Today", "http://www.utamap.com/showkasi.php?surl=65618" ],
  [ "卜學亮", "", "子曰", "https://mojim.com/twy100234x1x1.htm" ],
  [ "麻吉", "", "Jump 2003", "https://mojim.com/twy104695x2x2.htm" ],
  [ "小安", "", "憂愁", "https://mojim.com/twy102519x1x6.htm" ],
  [ "順子", "", "寫一首歌", "https://mojim.com/twy100129x9x3.htm" ],
  [ "初音ミク", "ピノキオP", "空想しょうもない日々", "http://www5.atwiki.jp/hmiku/pages/32492.html" ],
  [ "初音ミク", "まらしぃ", "月景色", "http://www5.atwiki.jp/hmiku/pages/16932.html" ],
  [ "上田祐司", "", "希望の宇宙の…", "http://j-lyric.net/artist/a04f531/l01ff4f.html" ],
  [ "ハンバートハンバート", "", "1時間", "http://j-lyric.net/artist/a0548cb/l030edc.html" ],
  [ "Angela Aki", "", "This Love", "http://www.kasi-time.com/item-1741.html" ],
  [ "ACIDMAN", "", "赤橙", "http://www.kasi-time.com/item-29312.html" ],
  [ "楊乃文", "", "我給的愛", "https://mojim.com/twy100142x2x7.htm" ],
  [ "江松霖", "", "要變成全世界最勇敢的人", "http://webptt.com/m.aspx?n=bbs/guitar/M.1444669501.A.948.html" ],
  [ "GUMI", "ささくれP", "tig-hug", "http://www5.atwiki.jp/hmiku/pages/30541.html" ],
  [ "初音ミク", "KEI", "ピエロ", "http://www5.atwiki.jp/hmiku/pages/10612.html" ],
  [ "EGOIST", "", "名前のない怪物", "http://www.kasi-time.com/item-64737.html" ],
  [ "GUMI", "buzzG", "星の唄", "http://www5.atwiki.jp/hmiku/pages/13837.html" ],
  [ "莫文蔚", "", "寂寞的戀人啊", "https://mojim.com/twy100098x22x12.htm" ],
  [ "江松霖", "", "我不害怕", "https://www.youtube.com/watch?v=MfvkbnyoZc8" ],
  [ "侯湘婷", "", "秋天別來", "https://mojim.com/twy100066x1x1.htm" ],
  [ "初音ミク", "電ポルP", "独りんぼエンヴィー", "http://www5.atwiki.jp/hmiku/pages/23582.html" ],
  [ "Supercell", "", "約束をしよう", "http://www.kasi-time.com/item-46405.html" ],
  [ "コニー", "", "しゃぼん玉 piano.ver", "http://www.nicovideo.jp/watch/sm17711964" ],
  [ "鄧麗君", "", "月亮代表我的心", "https://mojim.com/twy100463x71x8.htm" ],
  [ "Lia", "", "鳥の詩", "http://j-lyric.net/artist/a04f78c/l014f73.html" ],
  [ "大槻真希", "", "memories", "http://www.kasi-time.com/item-15871.html" ],
  [ "本田美奈子", "", "風のうた", "http://www.kasi-time.com/item-12379.html" ],
  [ "巡音ルカ・GUMI", "Easy Pop", "ハッピーシンセサイザ", "http://www5.atwiki.jp/hmiku/pages/13141.html" ],
  [ "初音ミクAppend", "yatsuhashi", "Opening Theme", "http://www5.atwiki.jp/hmiku/pages/10032.html" ],
  [ "", "", "fly me to the moon", "https://mojim.com/twy108260x7x1.htm" ],
  [ "神田沙也加/稲葉菜月/諸星すみれ", "", "雪だるま作ろう", "http://j-lyric.net/artist/a058c14/l0314ea.html" ],
  [ "謝安琪", "", "囍帖街", "https://mojim.com/twy104479x7x1.htm" ],
  [ "初音ミク", "想太", "「うそだよね」", "http://www5.atwiki.jp/hmiku/pages/23144.html" ],
  [ "Coldplay", "", "The Scientist", "http://www.metrolyrics.com/the-scientist-lyrics-coldplay.html" ],
  [ "Coldplay", "", "Yellow", "http://www.azlyrics.com/lyrics/coldplay/yellow.html" ],
  [ "歌愛ユキ", "想太", "「いかないで」", "http://www5.atwiki.jp/hmiku/pages/27027.html" ],
  [ "初音ミク", "ぽわぽわP", "そらのサカナ", "http://www5.atwiki.jp/hmiku/pages/12053.html" ],
  [ "FoZZtone", "", "ホールケーキ", "http://www.kasi-time.com/item-43374.html" ],
  [ "楊千嬅", "", "可惜我是水瓶座", "https://mojim.com/twy100143x32x15.htm" ],
  [ "初音ミク", "ぽわぽわP", "アストロノーツ", "http://www5.atwiki.jp/hmiku/pages/16410.html" ],
  [ "GUMI", "黒髪ストロングP", "林檎売りの泡沫少女", "http://www5.atwiki.jp/hmiku/pages/23451.html" ],
  [ "AKINO", "", "創聖のアクエリオン", "http://www.kasi-time.com/item-4110.html" ],
  [ "GUMI", "buzzG", "Fairytale,", "http://www5.atwiki.jp/hmiku/pages/22456.html" ],
  [ "巡音ルカ(ENG)", "baker", "「ARPK」", "http://www5.atwiki.jp/hmiku/pages/12047.html" ],
  [ "えり～な", "", "「ドキッ！こういうのが恋なの？」", "http://miraclestars.seesaa.net/article/175198669.html" ],
  [ "GUMI V3(English)", "Crusher-P", "ECHO", "http://www5.atwiki.jp/hmiku/pages/30536.html" ],
  [ "初音ミク", "ぽわぽわP", "ストロボライト", "http://www5.atwiki.jp/hmiku/pages/18115.html" ],
  [ "初音ミク", "のぼる↑P", "モノクロ∞ブルースカイ", "http://www5.atwiki.jp/hmiku/pages/9343.html" ],
  [ "初音ミク", "40㍍P", "トリノコシティ", "http://www5.atwiki.jp/hmiku/pages/11134.html" ],
  [ "v flower", "バルーン", "花瓶に触れた", "http://www5.atwiki.jp/hmiku/pages/33996.html" ],
  [ "初音ミクAppend", "トーマ", "オレンジ", "http://www5.atwiki.jp/hmiku/pages/23837.html" ],
  [ "偽物語", "", "白金ディスコ-Acoustic ver.-", "http://www.nicovideo.jp/watch/sm17331117" ],
  [ "東京事変", "", "遭難", "http://www.utamap.com/showkasi.php?surl=B07841" ],
  [ "鏡音リン", "ライブP", "S・K・Y", "http://www5.atwiki.jp/hmiku/pages/9949.html" ],
  [ "初音ミク", "40㍍P", "空中アクアリウム", "http://www5.atwiki.jp/hmiku/pages/10595.html" ],
  [ "Crispy脆樂團", "", "100分", "https://mojim.com/twy113323x1x4.htm" ],
  [ "河仁傑", "", "喜歡討厭你 feat.江松霖", "https://www.youtube.com/watch?v=-wU92CaRRjw" ],
  [ "林宥嘉", "", "兜圈", "https://mojim.com/twy105350x16x1.htm" ],
  [ "巡音ルカ", "ジミーサムP", "No Logic", "http://www5.atwiki.jp/hmiku/pages/6558.html" ],
  [ "江美琪", "", "雙手的溫柔", "https://mojim.com/twy100030x3x3.htm" ],
  [ "初音ミク", "電ポルP", "サイノウサンプラー Acoustic ver.", "http://www5.atwiki.jp/hmiku/pages/13167.html" ],
  [ "GUMI", "ささくれP", "カムパネルラ Piano ver.", "http://www5.atwiki.jp/hmiku/pages/7035.html" ],
  [ "藤木直人", "", "サンクフル☆エブリナイ", "http://www.kasi-time.com/item-19943.html" ],
  [ "氣志團", "", "One Night Carnival", "http://www.utamap.com/showkasi.php?surl=66593" ],
  [ "太妍", "", "I", "http://oops60213.pixnet.net/blog/post/437510335-taeyeon---i-feat.verbal-jint-%E4%B8%AD%E9%9F%93%E6%AD%8C%E8%A9%9E" ],
  [ "南方四賤客", "", "聖誕特集陀螺歌", "http://vlog.xuite.net/play/ZDlUWGV0LTM0MTA2MjEuZmx2/%E5%8D%97%E6%96%B9%E5%9B%9B%E8%B3%A4%E5%AE%A2-%E8%81%96%E8%AA%95%E7%89%B9%E9%9B%86%E9%99%80%E8%9E%BA%E6%AD%8C" ],
  [ "Spangle call Lilli line", "", "veek", "https://aslyrics.wordpress.com/lyrics/spangle-call-lilli-line/nanae-kanji/" ],
  [ "aiko", "", "スター", "http://www.utamap.com/showkasi.php?surl=B12251" ],
  [ "騎去哪", "", "吸到煙就罵幹", "https://www.youtube.com/watch?v=-P_ijntWKA8" ],
  [ "JUJU", "", "ナツノハナ", "http://www.kasi-time.com/item-14861.html" ],
  [ "Asian kung-fu generation", "", "君という花", "http://www.ufret.jp/song.php?data=2251" ],
  [ "相対性理論", "", "チャイナアドバイス", "http://www.ufret.jp/song.php?data=9728" ],
  [ "相対性理論", "", "(恋は)百年戦争", "j-lyric.net/artist/a04f804/l02012a.html" ],
  [ "初音ミク", "ねこぼーろ/ササノマリイ sasanomaly", "てのひらワンダーランド", "http://www5.atwiki.jp/hmiku/pages/31812.html" ],
  [ "初音ミク", "ねこぼーろ/ササノマリイ sasanomaly", "共感覚おばけ", "http://www5.atwiki.jp/hmiku/pages/32040.html" ],
  [ "初音ミク", "ねこぼーろ/ササノマリイ sasanomaly", "きかせたいのは", "http://www5.atwiki.jp/hmiku/pages/32149.html" ],
  [ "初音ミクAppend", "みきとP", "刹那プラス", "http://www5.atwiki.jp/hmiku/pages/21661.html" ],
  [ "中島美嘉", "", "雪の華", "https://mojim.com/twy102241x16x9.htm" ],
  [ "莫文蔚", "", "愛情", "https://mojim.com/twy100098x22x4.htm" ],
  [ "GUMI", "もじゃ", "ドナーソング", "http://www5.atwiki.jp/hmiku/pages/25058.html" ],
  [ "東京事変", "", "スーパースター", "http://www.utamap.com/showkasi.php?surl=B13007" ],
  [ "GUMI", "西沢さんP", "アセロラ", "http://www5.atwiki.jp/hmiku/pages/34184.html" ],
  [ "尹美萊 (太陽的後裔 OST)", "", "Always", "https://goo.gl/TdbSi8" ],
  [ "初音ミク", "ナブナ", "夜明けと蛍", "https://www5.atwiki.jp/hmiku/pages/30746.html" ],
  [ "GUMI", "もじゃ / 大柴広己", "さよならミッドナイト", "https://www5.atwiki.jp/hmiku/pages/18805.html" ],
  [ "", "", "為忙碌人製作的「大嘴鳥」", "https://www.youtube.com/watch?v=NNxEg8IJZhg" ],
  [ "萬能青年旅店", "", "殺死那個石家莊人", "https://mojim.com/twy109920x1x9.htm" ],
  [ "馬頔", "", "南山南", "https://mojim.com/twy142762x1x3.htm" ],
  [ "Lily Chou-Chou", "", "飛べない翼", "http://petitlyrics.com/lyrics/139049" ],
  [ "Lily Chou Chou", "", "空虚な石 / 共鳴", "http://petitlyrics.com/lyrics/139056" ],
  [ "あさきのくりむ童話", "", "去る金合戦", "https://www7.atwiki.jp/bemanilyrics/pages/1791.html" ],
  [ "初音ミク", "ピノキオP", "マッシュルームマザー", "https://www5.atwiki.jp/hmiku/pages/17718.html" ],
  [ "徐佳瑩", "", "你敢不敢", "https://mojim.com/twy105599x7x3.htm" ],
  [ "Cicada", "", "以一種假裝放蕩的矜持與你告別", "https://www.youtube.com/watch?v=KU28BTLeonQ" ],
  [ "pg.lost", "", "Yes I Am", "https://www.youtube.com/watch?v=C1XIa8IjN8o" ],
  [ "太妍 / TAEYEON / 태연", "", "11:11", "https://goo.gl/U2RfvS" ],
  [ "初音ミク", "瀬名航", "めんどくさいや", "https://www5.atwiki.jp/hmiku/pages/31595.html" ],
  [ "初音ミク", "ピノキオP", "きみも悪い人でよかった", "https://www5.atwiki.jp/hmiku/pages/34989.html" ],
  [ "初音ミク", "コウ", "ネアの幻遊", "https://www5.atwiki.jp/hmiku/pages/34984.html" ],
  [ "結月ゆかり", "黒澤まどか", "鳳仙花", "https://www5.atwiki.jp/hmiku/pages/28897.html" ],
  [ "初音ミク", "ぽわぽわP", "うたをうたうひと", "https://www5.atwiki.jp/hmiku/pages/22153.html" ],
  [ "GUMI", "ナポリP", "不完全な処遇", "https://www5.atwiki.jp/hmiku/pages/30985.html" ],
  [ "李千娜", "", "心花開", "https://mojim.com/twy109601x2x2.htm" ],
  [ "渋谷毅", "告白 Confession Original Soundtrack", "Milk", "http://www.autolyric.com/zh-hant/lyric/129719" ],
  [ "BECK", "", "I've got a feeling", "www.songlyrics.com/beck/i-ve-got-a-feeling-lyrics/" ],
  [ "BECK", "", "Follow me", "www.metrolyrics.com/follow-me-lyrics-beck.html" ],
  [ "朴樹", "", "平凡之路", "https://www.youtube.com/watch?v=NjTT5_RSkw4" ],
  [ "逃跑计划Escape Plan", "", "夜空中最亮的星", "https://www.youtube.com/watch?v=fzuy63eCUKc" ],
  [ "周杰倫", "", "稻香", "http://mojim.com/twy100951x27x11.htm" ],
  [ "周杰倫", "", "七里香", "https://mojim.com/twy100951x9x2.htm" ],
  [ "周杰倫", "", "愛在西元前", "https://mojim.com/twy100951x2x1.htm" ],
  [ "周杰倫", "", "半島鐵盒", "https://mojim.com/twy100951x5x2.htm" ],
  [ "周杰倫", "", "黑色幽默", "https://mojim.com/twy100951x1x6.htm" ],
  [ "周杰倫", "", "龍捲風", "https://mojim.com/twy100951x1x9.htm" ],
  [ "周杰倫", "", "爺爺泡的茶", "https://mojim.com/twy100951x5x7.htm" ],
  [ "周杰倫", "", "上海一九四三", "https://mojim.com/twy100951x6x16.htm" ],
  [ "周杰倫", "", "晴天", "https://mojim.com/twy100951x7x3.htm" ],
  [ "周杰倫", "", "星晴", "mojim.com/twy100951x6x14.htm" ],
  [ "周杰倫", "", "簡單愛", "https://mojim.com/twy100951x10x20.htm" ],
  [ "周杰倫", "", "安靜", "https://mojim.com/twy100951x6x10.htm" ],
  [ "周杰倫", "", "開不了口", "https://mojim.com/twy100951x2x5.htm" ],
  [ "周杰倫", "", "彩虹", "https://mojim.com/twy100951x22x2.htm" ],
  [ "周杰倫", "", "夜曲", "https://mojim.com/twy100951x17x1.htm" ],
  [ "周杰倫", "", "可愛女人", "https://mojim.com/twy100951x1x1.htm" ],
  [ "周杰倫", "", "給我一首歌的時間", "mojim.com/twy100951x27x2.htm" ],
  [ "陶喆", "", "黑色柳丁", "mojim.com/twy100207x4x1.htm" ],
  [ "陶喆", "", "小鎮姑娘", "https://mojim.com/twy100207x3x8.htm" ],
  [ "陶喆", "", "愛我還是他", "https://mojim.com/twy100207x7x6.htm" ],
  [ "whoo × ちょまいよ", "", "ワルツ / Waltz﻿", "https://www.youtube.com/watch?v=QtzEGdIHKnQ" ],
  [ "相対性理論", "", "四角革命", "https://mojim.com/twy108354x4x4.htm" ],
  [ "相対性理論", "", "学級崩壊", "https://mojim.com/twy108354x4x6.htm" ],
  [ "相対性理論", "", "ミス・パラレルワールド", "j-lyric.net/artist/a04f804/l020127.html" ],
  [ "相対性理論", "", "気になるあの娘", "j-lyric.net/artist/a04f804/l02012e.html" ],
  [ "相対性理論", "", "小学館", "j-lyric.net/artist/a04f804/l02012f.html" ],
  [ "フジファブリック", "", "若者のすべて", "www.utamap.com/showkasi.php?surl=B25719" ],
  [ "草東沒有派對", "", "山海", "https://mojim.com/twy163395x1x10.htm" ],
  [ "草東沒有派對", "", "大風吹", "https://mojim.com/twy163395x1x5.htm" ],
  [ "草東沒有派對", "", "爛泥", "https://www.youtube.com/watch?v=xbmCcFOUcsM" ],
  [ "草東沒有派對", "", "醜", "https://www.youtube.com/watch?v=uOwENjZRa4w" ],
  [ "宇多田ヒカル", "", "Goodbye Happiness", "www.kasi-time.com/item-51225.html" ],
  [ "阿肆", "", "預謀邂逅", "https://mojim.com/twy120519x1x3.htm" ],
  [ "阿肆", "", "我在人民廣場吃炸雞", "https://mojim.com/twy120519x1x7.htm" ],
  [ "蔡健雅", "", "別找我麻煩", "https://mojim.com/twy100166x19x6.htm" ],
  [ "Mandy", "Mr.Bartender 第三季 ED", "灼火", "https://www.ptt.cc/bbs/popmusic/M.1474016659.A.382.html" ],
  [ "ハンバートハンバート", "", "罪の味", "j-lyric.net/artist/a0548cb/l0232d2.html" ],
  [ "星野源", "", "フィルム", "www.kasi-time.com/item-59195.html" ],
  [ "星野源", "", "老夫婦", "https://mojim.com/twy110255x5x7.htm" ],
  [ "サカナクション", "", "新宝島", "j-lyric.net/artist/a04d6c9/l037b92.html" ],
  [ "サカナクション", "", "ミュージック", "j-lyric.net/artist/a04d6c9/l02b7d3.html" ],
  [ "サカナクション", "", "僕と花", "https://mojim.com/tw108127x7.htm" ],
  [ "フジファブリック", "", "Anthem", "j-lyric.net/artist/a033e7f/l01847d.html" ],
  [ "フジファブリック", "", "赤黄色の金木犀", "https://mojim.com/twy108819x18x1.htm" ],
  [ "椎名林檎", "", "歌舞伎町の女王", "www.utamap.com/showkasi.php?surl=65566" ],
  [ "椎名林檎", "", "17", "http://mojim.com/twy100613x13x10.htm" ],
  [ "椎名林檎", "", "茎(STEM)", "https://mojim.com/twy100613x5x5.htm" ],
  [ "椎名林檎 × 斉藤ネコ", "", "ハツコイ娼女", "www.utamap.com/showkasi.php?surl=B20990" ],
  [ "椎名林檎 × 斉藤ネコ", "", "意識 consciously", "j-lyric.net/artist/a00450a/l001c75.html" ],
  [ "amazarashi", "", "季節は次々死んでいく", "www.kasi-time.com/item-75108.html" ],
  [ "GUMI", "赤髪", "StarCrew", "https://www5.atwiki.jp/hmiku/pages/20453.html" ],
]
song.map! do |s|
  {
    singer: Singer.find_singer(s[0]),
    composer: Singer.find_singer(s[1]),
    title: s[2],
    title_translation: "",

    description: "",
    cover: "",
    feat: "",

    lyric_url: s[3],
    video_url: "",
  }
end
Song.create!(song)
